CREATE TABLE `APC` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`INTITULE` varchar(45) DEFAULT NULL,
	`ID_COMMUNE` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `APC_FK_COMMUNE` (`ID_COMMUNE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_AD_RECRUITMENT_PER_ORGANISM_RECRUITMENT` (
	`BIZ_AD_RECRUITMENT_PER_ORGANISM_RECRUITMENT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`BIZ_AD_RECRUITMENT_ID` bigint(20) DEFAULT NULL,
	`BIZ_RGANISM_RECRUITMENT_ID` bigint(20) DEFAULT NULL,
	PRIMARY KEY (`BIZ_AD_RECRUITMENT_PER_ORGANISM_RECRUITMENT_ID`),
	KEY `BIZ_FK_RECRU` (`BIZ_AD_RECRUITMENT_ID`),
	KEY `BIZ_FK_ORGAN` (`BIZ_RGANISM_RECRUITMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_AFFAIRE` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`DATE_CLOTURE` date DEFAULT NULL,
	`ETAPE_SUIVANTE` varchar(50) DEFAULT NULL,
	`ID_CLIENT` decimal(19,2) DEFAULT NULL,
	`ID_PHASE_VENTE` decimal(19,2) DEFAULT NULL,
	`MONTANT` decimal(18,2) DEFAULT NULL,
	`NOM_AFFAIRE` varchar(50) DEFAULT NULL,
	`PROBABILITE` int(11) DEFAULT NULL,
	`ID_DEVISE` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_AFFAIRE_DEVISE` (`ID_DEVISE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_AGENCE` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`INTITULE` varchar(45) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_APPEL` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`date` date DEFAULT NULL,
	`DESCRIPTION` longtext,
	`DUREE` int(11) DEFAULT NULL,
	`HEURE_DEBUT` varchar(50) DEFAULT NULL,
	`ID_CONTACT` int(11) DEFAULT NULL,
	`ID_USER` varchar(50) DEFAULT NULL,
	`NOTIFICATION` varchar(50) DEFAULT NULL,
	`STATUT_1` varchar(50) DEFAULT NULL,
	`SUJET` varchar(50) DEFAULT NULL,
	`ID_COMPTE` int(11) DEFAULT NULL,
	`ID_STATUT_REUNION` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_APPEL_COMPTE` (`ID_COMPTE`),
	KEY `BIZ_FK_APPEL_STATUT_REUNION` (`ID_STATUT_REUNION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_ARTICLE` (
	`AR_ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`AR_DATE_MODIF` date DEFAULT NULL,
	`AR_DESIGN` varchar(250) DEFAULT NULL,
	`AR_DESRIPTION` varchar(250) DEFAULT NULL,
	`AR_NATURE` varchar(50) DEFAULT NULL,
	`AR_REF` varchar(50) DEFAULT NULL,
	`PR_PRIXUNIT` decimal(18,2) DEFAULT NULL,
	`AR_SF_ID` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`AR_ID`),
	KEY `BIZ_FK_ARTICLE_SOUS_FAMILLE` (`AR_SF_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_BANQUE` (
	`CODE_BANQUE` varchar(45) NOT NULL,
	`ADRESSE_AGENCE` varchar(45) DEFAULT NULL,
	`CODE_AGENCE` varchar(45) DEFAULT NULL,
	`NOM_BANQUE` varchar(45) DEFAULT NULL,
	`STATUT_ACTIF_INACTIF` bit(1) DEFAULT NULL,
	PRIMARY KEY (`CODE_BANQUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_CAMPAGNE` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`DATE_DEBUT` date DEFAULT NULL,
	`DATE_FIN` date DEFAULT NULL,
	`DESCRIPTION` varchar(45) DEFAULT NULL,
	`INTITULE` varchar(45) DEFAULT NULL,
	`STATUT_COMPAGNE` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_CATEGORIE` (
	`CATEGORIE_ID` int(11) NOT NULL AUTO_INCREMENT,
	`INTITULE` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`CATEGORIE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_CATEGORIE_DOCUMENT` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`INTITULE` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_CATEGORIE_PANNEAU` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`CATEGORIE_PANNEAU` varchar(45) DEFAULT NULL,
	`INTITULE` varchar(45) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_CLIENT` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`ADRESSE_1` varchar(30) DEFAULT NULL,
	`ADRESSE_2` varchar(30) DEFAULT NULL,
	`CODE_POSTAL` varchar(6) DEFAULT NULL,
	`FAX` varchar(14) DEFAULT NULL,
	`ID_CONTACT` decimal(19,2) DEFAULT NULL,
	`ID_TYPE_COMPTE` int(11) DEFAULT NULL,
	`IDENTITE_FISCALE` varchar(50) DEFAULT NULL,
	`PAYS` longtext,
	`RAISON_SOCIALE` varchar(50) DEFAULT NULL,
	`REGION` varchar(50) DEFAULT NULL,
	`SITE_INTERNET` varchar(50) DEFAULT NULL,
	`TELEPHONE` varchar(14) DEFAULT NULL,
	`TELEPHONE_MOBILE` varchar(14) DEFAULT NULL,
	`VILLE` varchar(30) DEFAULT NULL,
	`ID_AFFAIRE` bigint(20) DEFAULT NULL,
	`ID_MAIL` bigint(20) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE KEY `BIZ_UK_CLIENT_MAIL` (`ID_MAIL`),
	KEY `BIZ_FK_CLIENT_AFFAIRE` (`ID_AFFAIRE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_COMMANDE` (
	`COMMAND_ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`DATE_CREATION` date DEFAULT NULL,
	`DATE_SOUHAITEE` date DEFAULT NULL,
	`MODE_PAIEMENT` varchar(50) DEFAULT NULL,
	`MOTIF` varchar(20) DEFAULT NULL,
	`NOM_PROJET` varchar(50) DEFAULT NULL,
	`REFFERENCE_CLIENT` varchar(50) DEFAULT NULL,
	`TYPE_CLIENT` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`COMMAND_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_COMMUNE` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`ID_REGION` int(11) DEFAULT NULL,
	`INTITULE` varchar(45) DEFAULT NULL,
	`ID_WILAYA` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_COMMUNE_WILAYA` (`ID_WILAYA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_COMPTE_BANCAIRE` (
	`NOM_BANQUE` varchar(45) NOT NULL,
	`ADRESSE_AGENCE` varchar(45) DEFAULT NULL,
	`CLE` int(11) DEFAULT NULL,
	`CODE_AGENCE` int(11) DEFAULT NULL,
	`CODE_BANQUE` int(11) DEFAULT NULL,
	`CODE_BIC` int(11) DEFAULT NULL,
	`CODE_IBAN` varchar(45) DEFAULT NULL,
	`NUM_COMPTE` int(11) DEFAULT NULL,
	`STATUT_ACTIF_INACTIF` bit(1) DEFAULT NULL,
	PRIMARY KEY (`NOM_BANQUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_CONDIDATE_PER_AD_RECRUITMENT` (
	`BIZ_CONDIDATE_PER_AD_RECRUITMENT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`BIZ_AD_RECRUITMENT` bigint(20) DEFAULT NULL,
	`BIZ_CONDIDATE_ID` bigint(20) DEFAULT NULL,
	PRIMARY KEY (`BIZ_CONDIDATE_PER_AD_RECRUITMENT_ID`),
	KEY `BIZ_FK_RECRUTEMENT` (`BIZ_AD_RECRUITMENT`),
	KEY `BIZ_FK_CANDIDATE` (`BIZ_CONDIDATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_CONTACTS` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`CIVILITE` varchar(45) DEFAULT NULL,
	`EMAIL` varchar(45) DEFAULT NULL,
	`FONCTION` varchar(50) DEFAULT NULL,
	`NOM` varchar(50) DEFAULT NULL,
	`PRENOM` varchar(50) DEFAULT NULL,
	`TELEPHONE_FAX` varchar(14) DEFAULT NULL,
	`TELEPHONE_FIXE` varchar(14) DEFAULT NULL,
	`TELEPHONE_PORTABLE` varchar(14) DEFAULT NULL,
	`USER_NAME` varchar(50) DEFAULT NULL,
	`ID_CLIENT` bigint(20) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_CONTACTS_CLIENT` (`ID_CLIENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_CONTRAT` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`DESCRIPTION` longtext,
	`TITRE` varchar(45) DEFAULT NULL,
	`ID_CLIENT` int(11) DEFAULT NULL,
	`ID_TYPE_CONTRAT` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_CONTRAT_CLIENT` (`ID_CLIENT`),
	KEY `BIZ_FK_CONTRAT_TYPE` (`ID_TYPE_CONTRAT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_CONTRAT_EMPLACEMENT` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`DATE_DEBUT` date DEFAULT NULL,
	`DATE_FIN` date DEFAULT NULL,
	`ID_TYPE` varchar(45) DEFAULT NULL,
	`STATUT_CONTRAT` varchar(45) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_COURRIER_RECOUVREMENT` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`AC` bit(1) DEFAULT NULL,
	`DATE_COURRIER` date DEFAULT NULL,
	`MONTANT_A_REGLE` decimal(18,2) DEFAULT NULL,
	`N_CHRONO` int(11) DEFAULT NULL,
	`NIVEAU` int(11) DEFAULT NULL,
	`ID_FACTURE` bigint(20) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_COURRIER_RECOUVREMENT_FACTURE` (`ID_FACTURE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_DATE_POSE` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`DATE_POSE_PREVISIONELLE` date DEFAULT NULL,
	`DATE_POSE_RIELLE` date DEFAULT NULL,
	`ID_TYPE_POSE` varchar(45) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_DEVISE` (
	`ID` int(11) NOT NULL,
	`INTITULE` varchar(50) NOT NULL,
	`NOM_DEVISE` varchar(5) NOT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_DOCUMENT_CLIENT` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`DATE_PUBLICATION` date DEFAULT NULL,
	`DESCRIPTION` longtext,
	`FILE_ABSOLUTE_NAME` varchar(50) DEFAULT NULL,
	`ID_STATUT` decimal(19,2) DEFAULT NULL,
	`NOM_DOCUMENT` varchar(50) DEFAULT NULL,
	`NOM_FICHIER` varchar(50) DEFAULT NULL,
	`VERSION` varchar(5) DEFAULT NULL,
	`ID_CATEGORIE` bigint(20) DEFAULT NULL,
	`ID_COMPTE` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_DOCUMENT_CATEGORIE` (`ID_CATEGORIE`),
	KEY `BIZ_FK_DOCUMENT_COMPTE` (`ID_COMPTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_DOC_BIBLIOTHEQUE` (
	`BIBLIOTHEQUE_ID` int(11) NOT NULL AUTO_INCREMENT,
	`INTITULE` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`BIBLIOTHEQUE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_ECHEANCE_PAIEMENT` (
	`ID_` int(11) NOT NULL AUTO_INCREMENT,
	`DATE_ECHEANCE` date DEFAULT NULL,
	`DATE_REELLE_REGLEMENT` date DEFAULT NULL,
	`DEROGATION_PAIEMENT` bit(1) DEFAULT NULL,
	`ID_CLIENT` varchar(10) DEFAULT NULL,
	`MONTANT_A_REGLER` decimal(18,2) DEFAULT NULL,
	`MONTANT_REGLER` decimal(18,2) DEFAULT NULL,
	`POURCENTAGE` decimal(2,2) DEFAULT NULL,
	`RESTE_A_REGLER` decimal(18,2) DEFAULT NULL,
	`STATUT` varchar(50) DEFAULT NULL,
	`STATUT_PAIEMENT` bit(1) DEFAULT NULL,
	`ID_FACTURE` bigint(20) DEFAULT NULL,
	PRIMARY KEY (`ID_`),
	KEY `BIZ_FK_PAIEMENT_FACTURE` (`ID_FACTURE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_EMPLACEMENT` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`ADRESSE` varchar(45) DEFAULT NULL,
	`CIBLE` varchar(45) DEFAULT NULL,
	`NOMBRE_POPULATION` varchar(45) DEFAULT NULL,
	`NUM_FACE` varchar(45) DEFAULT NULL,
	`PROSPECTION_CRITERES` varchar(45) DEFAULT NULL,
	`PROSPECTION_OBSERVATION` varchar(45) DEFAULT NULL,
	`PROSPECTION_ORDER` varchar(45) DEFAULT NULL,
	`PROSPECTION_PROPOSITION` varchar(45) DEFAULT NULL,
	`SOURCE_ALIMENTATION` varchar(45) DEFAULT NULL,
	`STATUT` varchar(45) DEFAULT NULL,
	`VISIBILITE` varchar(45) DEFAULT NULL,
	`ID_MODELE_PANNEAU` int(11) DEFAULT NULL,
	`ID_CATEGORIE_PANNEAU` int(11) DEFAULT NULL,
	`ID_CONTRAT_EMPLACEMENT` int(11) DEFAULT NULL,
	`ID_DATE_POSE` int(11) DEFAULT NULL,
	`ID_FACE_PANNEAU` int(11) DEFAULT NULL,
	`ID_PHOTO_EMPLACEMENT` int(11) DEFAULT NULL,
	`ID_SOUS_TRAITAN_INSTALATEUR` int(11) DEFAULT NULL,
	`ID_TYPE_PANNEAU` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_EMPLACEMENT_MODELE_PANNEAU` (`ID_MODELE_PANNEAU`),
	KEY `BIZ_FK_EMPLACEMENT_CATEGORIE` (`ID_CATEGORIE_PANNEAU`),
	KEY `BIZ_FK_EMPLACEMENT_CONTRAT` (`ID_CONTRAT_EMPLACEMENT`),
	KEY `BIZ_FK_EMPLACEMENT_DATE_POSE` (`ID_DATE_POSE`),
	KEY `BIZ_FK_EMPLACEMENT_FACE_PANNEAU` (`ID_FACE_PANNEAU`),
	KEY `BIZ_FK_EMPLACEMENT_PHOTO` (`ID_PHOTO_EMPLACEMENT`),
	KEY `BIZ_FK_EMPLACEMENT_SOUS_TRAITANT` (`ID_SOUS_TRAITAN_INSTALATEUR`),
	KEY `BIZ_FK_EMPLACEMENT_TYPE` (`ID_TYPE_PANNEAU`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_FACE_PANNEAU` (
	`FACE_PANNEAU` int(11) NOT NULL AUTO_INCREMENT,
	`HAUTEUR` int(11) DEFAULT NULL,
	`ID` decimal(19,2) DEFAULT NULL,
	`LARGEUR` int(11) DEFAULT NULL,
	`NUMERO` varchar(20) DEFAULT NULL,
	PRIMARY KEY (`FACE_PANNEAU`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_FACTURE` (
	`ID_FACTURE` bigint(20) NOT NULL AUTO_INCREMENT,
	`CONDITION_PAIEMENT` varchar(50) DEFAULT NULL,
	`DATE_FACTURE` date DEFAULT NULL,
	`DATE_RAPPEL` date DEFAULT NULL,
	`DEROGATION_FACTURE` bit(1) DEFAULT NULL,
	`DESCRIPTION` varchar(250) DEFAULT NULL,
	`ECHEANCE_REGLEMENT` date DEFAULT NULL,
	`ID_CLIENT` int(11) DEFAULT NULL,
	`INTITULE_CLIENT` varchar(50) DEFAULT NULL,
	`MONTANT_A_REGLE` decimal(18,2) DEFAULT NULL,
	`MONTANT_HT` decimal(18,2) DEFAULT NULL,
	`MONTANT_TVA` decimal(18,2) DEFAULT NULL,
	`N_CLIENT` int(11) DEFAULT NULL,
	`N_PIECE` decimal(19,2) DEFAULT NULL,
	`PRIX_UNITAIRE_HT` decimal(18,2) DEFAULT NULL,
	`QUALIFIE` bit(1) DEFAULT NULL,
	`QUANTITE` int(11) DEFAULT NULL,
	`REFERENCE` varchar(50) DEFAULT NULL,
	`SORTIE_STOCK` varchar(50) DEFAULT NULL,
	`TIMBRE` decimal(18,2) DEFAULT NULL,
	`TOTAL_HT` decimal(18,2) DEFAULT NULL,
	`TOTAL_TTC` decimal(18,2) DEFAULT NULL,
	`TYPE` varchar(50) DEFAULT NULL,
	`MODE_REGLEMENT` int(11) DEFAULT NULL,
	`STATUT_FACTURE` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID_FACTURE`),
	KEY `BIZ_FK_FACTURE_MODE_REGLEMENT` (`MODE_REGLEMENT`),
	KEY `BIZ_FK_FACTURE_STATUT_FACTURE` (`STATUT_FACTURE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_FAMILLE` (
	`CODE_FAMILLE` int(11) NOT NULL,
	`DATE_MODIF` varchar(250) DEFAULT NULL,
	`FA_CODE_FAMILLE` varchar(50) DEFAULT NULL,
	`FA_DATE_MODIF` date DEFAULT NULL,
	`FA_ID` bigint(20) NOT NULL,
	`FA_INTITULE` varchar(250) DEFAULT NULL,
	`ID_RAYON` decimal(19,2) DEFAULT NULL,
	`INTITULE` varchar(45) DEFAULT NULL,
	PRIMARY KEY (`CODE_FAMILLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_FAMILLE_ACHETEUR` (
	`ID_FA` bigint(20) NOT NULL AUTO_INCREMENT,
	`PA_ID_ACHETEUR` varchar(64) DEFAULT NULL,
	`PA_ID_FAMILLE` decimal(19,2) DEFAULT NULL,
	PRIMARY KEY (`ID_FA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_FOURNISSEUR` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`ADRESSE` varchar(50) DEFAULT NULL,
	`ADRESSE_SITE_INTERNET` varchar(45) DEFAULT NULL,
	`CIF` varchar(45) DEFAULT NULL,
	`CODE_FOURNISSEUR` varchar(45) DEFAULT NULL,
	`DATE_MODIF` date DEFAULT NULL,
	`DEVISE_FOURNISSEUR` varchar(45) DEFAULT NULL,
	`INTITULE` varchar(250) DEFAULT NULL,
	`MAIL` varchar(250) DEFAULT NULL,
	`NIF` varchar(45) DEFAULT NULL,
	`NOM_COMMERCIAL` varchar(45) DEFAULT NULL,
	`NOM_HABITUEL` varchar(45) DEFAULT NULL,
	`NUM_ARTICLE_IMPOSITION` varchar(45) DEFAULT NULL,
	`NUM_REGISTRE_COMMERCE` varchar(45) DEFAULT NULL,
	`TVA` varchar(45) DEFAULT NULL,
	`TYPE_FOURNISSEUR` int(11) DEFAULT NULL,
	`UK` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_GROUP_RESPONSABLE` (
	`ID_GR` int(11) NOT NULL AUTO_INCREMENT,
	`ID_RESPONSABLE` varchar(64) DEFAULT NULL,
	`ID_USER` varchar(64) DEFAULT NULL,
	PRIMARY KEY (`ID_GR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_LIGNE_COMMANDE` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`DESCRIPTION` varchar(250) DEFAULT NULL,
	`ID_CATEGORIE` int(11) DEFAULT NULL,
	`ID_PROCESS` decimal(19,2) DEFAULT NULL,
	`ID_PRODUIT` decimal(19,2) DEFAULT NULL,
	`MONTANT_HT` decimal(18,2) DEFAULT NULL,
	`PRIX_NEGOC` decimal(18,2) DEFAULT NULL,
	`PRIX_UNITAIRE_HT` decimal(18,2) DEFAULT NULL,
	`QUANTITE` int(11) DEFAULT NULL,
	`TOTAL` decimal(18,2) DEFAULT NULL,
	`TVA` decimal(18,2) DEFAULT NULL,
	`ID_ARTICLE` bigint(20) DEFAULT NULL,
	`ID_COMMAND` bigint(20) DEFAULT NULL,
	`ID_FAMILLE` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_LIGNE_COMMANDE_ARTICLE` (`ID_ARTICLE`),
	KEY `BIZ_FK_LIGNE_COMMANDE_COMMAND` (`ID_COMMAND`),
	KEY `BIZ_FK_LIGNE_COMMANDE_FAMILLE` (`ID_FAMILLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_LIGNE_FOURNISSEUR` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`ID_PROCESS` decimal(19,2) DEFAULT NULL,
	`ID_COMMAND` bigint(20) DEFAULT NULL,
	`ID_FOURNISSEUR` bigint(20) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_LIGNE_FOURNISSEUR_COMMAND` (`ID_COMMAND`),
	KEY `BIZ_FK_LIGNE_FOURNISSEUR_FOURNISSEUR` (`ID_FOURNISSEUR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_MAGASIN` (
	`ID_MAGASIN` bigint(20) NOT NULL AUTO_INCREMENT,
	`ADRESSE` varchar(50) DEFAULT NULL,
	`COORDONNEES_GEO` varchar(20) DEFAULT NULL,
	`INTITULE` varchar(50) DEFAULT NULL,
	`TELEPHONE` varchar(14) DEFAULT NULL,
	`SECTEUR` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID_MAGASIN`),
	KEY `BIZ_FK_MAGASIN_SECTEUR` (`SECTEUR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_MAIL` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`CONTENU` longtext,
	`DATE_ENVOI` date DEFAULT NULL,
	`EXPEDITEUR` varchar(50) DEFAULT NULL,
	`RECEPTEUR` varchar(50) DEFAULT NULL,
	`SUJET` varchar(50) DEFAULT NULL,
	`ID_MODELE_MAIL` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_MAIL_MODELE` (`ID_MODELE_MAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_MEDIA` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`DESCRIPTION` varchar(50) DEFAULT NULL,
	`NOM` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_MODELE_MAIL` (
	`Id` int(11) NOT NULL AUTO_INCREMENT,
	`mail` longtext,
	`titre` varchar(250) DEFAULT NULL,
	`typeMail` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_MODELE_PANNEAU` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`INTITULE` varchar(45) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_MODE_REGLEMENT` (
	`ID_MODE_REGLEMENT` int(11) NOT NULL AUTO_INCREMENT,
	`INTITULE_MODE_REGLEMENT` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`ID_MODE_REGLEMENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_OPERATION` (
	`ID_OPERATION` int(11) NOT NULL AUTO_INCREMENT,
	`ANIMATION` varchar(50) DEFAULT NULL,
	`ARTICLE` decimal(18,2) DEFAULT NULL,
	`DATE_COMMUNICATION_BRIEF` date DEFAULT NULL,
	`DATE_DEBUT` date DEFAULT NULL,
	`DATE_DEBUT_REEL` date DEFAULT NULL,
	`DATE_FIN_PREVISIONNELLE` date DEFAULT NULL,
	`DATE_FIN_REEL` date DEFAULT NULL,
	`DATE_PROPOSITION_OFFRE` date DEFAULT NULL,
	`DATE_REMONTE_ENGAGEMENTS` date DEFAULT NULL,
	`DATE_RETOUR_LISTE_DEFINITIVE` date DEFAULT NULL,
	`DECROCHAGE_CLIENT` int(11) DEFAULT NULL,
	`DEPARTEMENT` varchar(50) DEFAULT NULL,
	`DESCRIPTION` varchar(50) DEFAULT NULL,
	`EAN` varchar(50) DEFAULT NULL,
	`ECART_CAISSE` decimal(18,2) DEFAULT NULL,
	`ENGAGEMENT_MAGAZIN` varchar(50) DEFAULT NULL,
	`FAMILLE` varchar(50) DEFAULT NULL,
	`ID_FOURNISSEUR` int(11) DEFAULT NULL,
	`INTITULE` varchar(50) DEFAULT NULL,
	`LIVRE` varchar(50) DEFAULT NULL,
	`MANQUE_GAGNER_EN_CA` decimal(18,2) DEFAULT NULL,
	`MANQUE_GAGNER_EN_MARGE_ARRIERE` decimal(18,2) DEFAULT NULL,
	`MANQUE_GAGNER_EN_MARGE_AVANT` decimal(18,2) DEFAULT NULL,
	`MARGE` varchar(50) DEFAULT NULL,
	`MARQUE` varchar(50) DEFAULT NULL,
	`MIN_COMMANDE` decimal(18,2) DEFAULT NULL,
	`MOIS` int(11) DEFAULT NULL,
	`NON_LIVRE` varchar(50) DEFAULT NULL,
	`OPERATION_INTITULE` varchar(50) DEFAULT NULL,
	`PA_PROGRAMME` varchar(50) DEFAULT NULL,
	`PAN` decimal(18,2) DEFAULT NULL,
	`PAP` decimal(18,2) DEFAULT NULL,
	`POS` varchar(50) DEFAULT NULL,
	`PVN` decimal(18,2) DEFAULT NULL,
	`PVP` decimal(18,2) DEFAULT NULL,
	`RAYON` varchar(50) DEFAULT NULL,
	`REMISE` decimal(18,2) DEFAULT NULL,
	`TG_PODIUM` varchar(50) DEFAULT NULL,
	`UNITE_DE_BESOIN` decimal(18,2) DEFAULT NULL,
	PRIMARY KEY (`ID_OPERATION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_PHOTO_EMPLACEMENT` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`DESCRIPTION` varchar(45) DEFAULT NULL,
	`INTITULE` varchar(45) DEFAULT NULL,
	`TYPE` varchar(45) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_PHASE_VENTE` (
	`ID_PHASE_VENTE` bigint(20) NOT NULL AUTO_INCREMENT,
	`INTITULE` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`ID_PHASE_VENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_PLAN_MEDIA` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`ANNONCE` varchar(50) DEFAULT NULL,
	`CANAL` varchar(50) DEFAULT NULL,
	`DATE_CREATION` date DEFAULT NULL,
	`DATE_DIFFUSION` date DEFAULT NULL,
	`DESCRIPTION` varchar(50) DEFAULT NULL,
	`DUREE` int(11) DEFAULT NULL,
	`ECRAN` varchar(50) DEFAULT NULL,
	`FORMAT` varchar(50) DEFAULT NULL,
	`HORAIRE` varchar(50) DEFAULT NULL,
	`INTITULE` varchar(50) DEFAULT NULL,
	`JOURS` int(11) DEFAULT NULL,
	`PRIXACHATAFACTURER` bit(1) DEFAULT NULL,
	`PRIXVENTECLIENT` bit(1) DEFAULT NULL,
	`PU_MAJORE` varchar(50) DEFAULT NULL,
	`QTE` varchar(50) DEFAULT NULL,
	`ST_ANOMALIE` bit(1) DEFAULT NULL,
	`ST_DECALAGE` bit(1) DEFAULT NULL,
	`ST_FACTURABLECLIENT` bit(1) DEFAULT NULL,
	`ST_FACTURABLEFOURNISSEUR` bit(1) DEFAULT NULL,
	`ST_MOTIFCOMMENTAIRE` bit(1) DEFAULT NULL,
	`ST_NEGOCIECLIENT` bit(1) DEFAULT NULL,
	`ST_NEGOCIEFOURNISSEUR` bit(1) DEFAULT NULL,
	`ST_OK` bit(1) DEFAULT NULL,
	`ST_PASSAGE` bit(1) DEFAULT NULL,
	`ST_PROGRAMME` bit(1) DEFAULT NULL,
	`ST_STANDBY` bit(1) DEFAULT NULL,
	`TOTALE` decimal(18,2) DEFAULT NULL,
	`ID_COMPAGNIE` int(11) DEFAULT NULL,
	`ID_FACTURE` bigint(20) DEFAULT NULL,
	`ID_PRODUIT` bigint(20) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_PLAN_MEDIA_COMPAGNIE` (`ID_COMPAGNIE`),
	KEY `BIZ_FK_PLAN_MEDIA_FACTURE` (`ID_FACTURE`),
	KEY `BIZ_FK_PLAN_MEDIA_PRODUIT` (`ID_PRODUIT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_PLAN_MEDIA_OOH` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`ADRESSE` varchar(255) DEFAULT NULL,
	`ANNEE` varchar(255) DEFAULT NULL,
	`ANNONCEUR` varchar(255) DEFAULT NULL,
	`APC` varchar(255) DEFAULT NULL,
	`CLIENT` varchar(255) DEFAULT NULL,
	`COMPAGNE` varchar(255) DEFAULT NULL,
	`DATE_DEBUT` varchar(255) DEFAULT NULL,
	`DATE_FIN` varchar(255) DEFAULT NULL,
	`DUREE` varchar(255) DEFAULT NULL,
	`FOURNISSEUR` varchar(255) DEFAULT NULL,
	`MARGE_BRUT` varchar(255) DEFAULT NULL,
	`MESSAGE` varchar(255) DEFAULT NULL,
	`MOIS` varchar(255) DEFAULT NULL,
	`NUM_BC_CLIENT` varchar(255) DEFAULT NULL,
	`NUM_BC_FOURNISSEUR` varchar(255) DEFAULT NULL,
	`NUM_DEVIS_MAA` varchar(255) DEFAULT NULL,
	`PARC` varchar(255) DEFAULT NULL,
	`PRIXACHATAFACTURER` bit(1) DEFAULT NULL,
	`PRIXVENTECLIENT` bit(1) DEFAULT NULL,
	`PRODUIT` varchar(255) DEFAULT NULL,
	`PU_IMPRESSION_ACHAT` varchar(255) DEFAULT NULL,
	`PU_IMPRESSION_VENTE` varchar(255) DEFAULT NULL,
	`PU_LOCATION_ACHAT` varchar(255) DEFAULT NULL,
	`PU_LOCATION_VENTE` varchar(255) DEFAULT NULL,
	`QTE` varchar(255) DEFAULT NULL,
	`REMARQUE` varchar(255) DEFAULT NULL,
	`REMISE_LOCATION_ACHAT` varchar(255) DEFAULT NULL,
	`REMISE_LOCATION_VENTE` varchar(255) DEFAULT NULL,
	`ST_ANOMALIE` bit(1) DEFAULT NULL,
	`ST_DECALAGE` bit(1) DEFAULT NULL,
	`ST_FACTURABLECLIENT` bit(1) DEFAULT NULL,
	`ST_FACTURABLEFOURNISSEUR` bit(1) DEFAULT NULL,
	`ST_MOTIFCOMMENTAIRE` bit(1) DEFAULT NULL,
	`ST_NEGOCIECLIENT` bit(1) DEFAULT NULL,
	`ST_NEGOCIEFOURNISSEUR` bit(1) DEFAULT NULL,
	`ST_OK` bit(1) DEFAULT NULL,
	`ST_PASSAGE` bit(1) DEFAULT NULL,
	`ST_PROGRAMME` bit(1) DEFAULT NULL,
	`ST_STANDBY` bit(1) DEFAULT NULL,
	`SUPPORT` varchar(255) DEFAULT NULL,
	`SURFACE_ACHAT` varchar(255) DEFAULT NULL,
	`SURFACE_VENTE` varchar(255) DEFAULT NULL,
	`TOTAL_BRUT_LOCATION_ACHAT` varchar(255) DEFAULT NULL,
	`TOTAL_BRUT_LOCATION_VENTE` varchar(255) DEFAULT NULL,
	`TOTAL_GLOBAL_ACHAT` varchar(255) DEFAULT NULL,
	`TOTAL_GLOBAL_VENTE` varchar(255) DEFAULT NULL,
	`TOTAL_NET_IMPRESSION_ACHAT` varchar(255) DEFAULT NULL,
	`TOTAL_NET_IMPRESSION_VENTE` varchar(255) DEFAULT NULL,
	`TOTAL_NET_LOCATION_ACHAT` varchar(255) DEFAULT NULL,
	`TOTAL_NET_LOCATION_VENTE` varchar(255) DEFAULT NULL,
	`TVA_ACHAT` varchar(255) DEFAULT NULL,
	`TVA_VENTE` varchar(255) DEFAULT NULL,
	`TYPE` varchar(255) DEFAULT NULL,
	`WILAYA` varchar(255) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_PLAN_MEDIA_PRESS` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`ANNONCEUR` varchar(255) DEFAULT NULL,
	`CLIENT` varchar(255) DEFAULT NULL,
	`COMISSION_AGENCE` varchar(255) DEFAULT NULL,
	`COMPAGNE` varchar(255) DEFAULT NULL,
	`DATE` varchar(255) DEFAULT NULL,
	`FORMAT` varchar(255) DEFAULT NULL,
	`INCIDENT` varchar(255) DEFAULT NULL,
	`MARGE_BRUT` varchar(255) DEFAULT NULL,
	`MESSAGE` varchar(255) DEFAULT NULL,
	`MOIS` varchar(255) DEFAULT NULL,
	`NU_BC_CLIENT` varchar(255) DEFAULT NULL,
	`NU_BC_FOURNISSEUR` varchar(255) DEFAULT NULL,
	`NUM_FACT_ACHAT` varchar(255) DEFAULT NULL,
	`PRIX_ACHAT_HT` varchar(255) DEFAULT NULL,
	`PRIX_ACHAT_NET` varchar(255) DEFAULT NULL,
	`PRIX_ACHAT_TTC` varchar(255) DEFAULT NULL,
	`PRIX_VENTE_HT` varchar(255) DEFAULT NULL,
	`PRIX_VENTE_NET` varchar(255) DEFAULT NULL,
	`PRIXACHATAFACTURER` bit(1) DEFAULT NULL,
	`PRIXVENTECLIENT` bit(1) DEFAULT NULL,
	`PRODUIT` varchar(255) DEFAULT NULL,
	`PU_ACHAT` varchar(255) DEFAULT NULL,
	`PU_VENTE` varchar(255) DEFAULT NULL,
	`QTE_ACHAT` varchar(255) DEFAULT NULL,
	`QTE_VENTE` varchar(255) DEFAULT NULL,
	`REMARQUE` varchar(255) DEFAULT NULL,
	`REMISE_ACHAT` varchar(255) DEFAULT NULL,
	`REMISE_VENTE` varchar(255) DEFAULT NULL,
	`ST_ANOMALIE` bit(1) DEFAULT NULL,
	`ST_DECALAGE` bit(1) DEFAULT NULL,
	`ST_FACTURABLECLIENT` bit(1) DEFAULT NULL,
	`ST_FACTURABLEFOURNISSEUR` bit(1) DEFAULT NULL,
	`ST_MOTIFCOMMENTAIRE` bit(1) DEFAULT NULL,
	`ST_NEGOCIECLIENT` bit(1) DEFAULT NULL,
	`ST_NEGOCIEFOURNISSEUR` bit(1) DEFAULT NULL,
	`ST_OK` bit(1) DEFAULT NULL,
	`ST_PASSAGE` bit(1) DEFAULT NULL,
	`ST_PROGRAMME` bit(1) DEFAULT NULL,
	`ST_STANDBY` bit(1) DEFAULT NULL,
	`TITRE` varchar(255) DEFAULT NULL,
	`TOTAL_BRUT_ACHAT` varchar(255) DEFAULT NULL,
	`TOTAL_BRUT_VENTE` varchar(255) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_PLAN_MEDIA_RADIO` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`ANNONCEUR` varchar(255) DEFAULT NULL,
	`BRUT_ACHAT` varchar(255) DEFAULT NULL,
	`BRUT_VENTE` varchar(255) DEFAULT NULL,
	`CHAINE` varchar(255) DEFAULT NULL,
	`CLIENT` varchar(255) DEFAULT NULL,
	`COMMISSION_AGENCE` varchar(255) DEFAULT NULL,
	`COMPAGNE` varchar(255) DEFAULT NULL,
	`DATE_DEBUT` varchar(255) DEFAULT NULL,
	`DATE_FIN` varchar(255) DEFAULT NULL,
	`DUREE` varchar(255) DEFAULT NULL,
	`ECRAN` varchar(255) DEFAULT NULL,
	`HEUR` varchar(255) DEFAULT NULL,
	`INCIDENT` varchar(255) DEFAULT NULL,
	`MARGE_BRUT_MAA` varchar(255) DEFAULT NULL,
	`MESSAGE` varchar(255) DEFAULT NULL,
	`NET_ACHAT` varchar(255) DEFAULT NULL,
	`NET_VENTE` varchar(255) DEFAULT NULL,
	`NUM_BC_CLIENT` varchar(255) DEFAULT NULL,
	`NUM_BC_FOURNISSEUR` varchar(255) DEFAULT NULL,
	`NUM_FACTURE_ACHAT` varchar(255) DEFAULT NULL,
	`PRIXACHATAFACTURER` bit(1) DEFAULT NULL,
	`PRIXVENTECLIENT` bit(1) DEFAULT NULL,
	`PRODUIT` varchar(255) DEFAULT NULL,
	`PROGRAMME` varchar(255) DEFAULT NULL,
	`REMARQUE` varchar(255) DEFAULT NULL,
	`REMISE_ACHAT` varchar(255) DEFAULT NULL,
	`REMISE_VENTE` varchar(255) DEFAULT NULL,
	`ST_ANOMALIE` bit(1) DEFAULT NULL,
	`ST_DECALAGE` bit(1) DEFAULT NULL,
	`ST_FACTURABLECLIENT` bit(1) DEFAULT NULL,
	`ST_FACTURABLEFOURNISSEUR` bit(1) DEFAULT NULL,
	`ST_MOTIFCOMMENTAIRE` bit(1) DEFAULT NULL,
	`ST_NEGOCIECLIENT` bit(1) DEFAULT NULL,
	`ST_NEGOCIEFOURNISSEUR` bit(1) DEFAULT NULL,
	`ST_OK` bit(1) DEFAULT NULL,
	`ST_PASSAGE` bit(1) DEFAULT NULL,
	`ST_PROGRAMME` bit(1) DEFAULT NULL,
	`ST_STANDBY` bit(1) DEFAULT NULL,
	`TOTAL_COM_AGENCE` varchar(255) DEFAULT NULL,
	`TYPE_ACHAT` varchar(255) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_PLAN_MEDIA_TV` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`ANNONCEUR` varchar(255) DEFAULT NULL,
	`CHAINE` varchar(255) DEFAULT NULL,
	`CLIENT` varchar(255) DEFAULT NULL,
	`COMMISION_AGENCE` varchar(255) DEFAULT NULL,
	`COMPAGNE` varchar(255) DEFAULT NULL,
	`DATE_DEBUT` varchar(255) DEFAULT NULL,
	`DATE_FIN` varchar(255) DEFAULT NULL,
	`ECRAN` varchar(255) DEFAULT NULL,
	`FORMAT` varchar(255) DEFAULT NULL,
	`HEUR` varchar(255) DEFAULT NULL,
	`INCIDENT` varchar(255) DEFAULT NULL,
	`MARGE_BRUT` varchar(255) DEFAULT NULL,
	`MESSAGE` varchar(255) DEFAULT NULL,
	`MOIS` varchar(255) DEFAULT NULL,
	`NUM_BC_Client` varchar(255) DEFAULT NULL,
	`NUM_BC_FOURNISSEUR` varchar(255) DEFAULT NULL,
	`NUM_FACT_ACHAT` varchar(255) DEFAULT NULL,
	`PRIX_ACHAT_HT` varchar(255) DEFAULT NULL,
	`PRIX_ACHAT_NET` varchar(255) DEFAULT NULL,
	`PRIX_ACHAT_TTC` varchar(255) DEFAULT NULL,
	`PRIX_VENTE_HT` varchar(255) DEFAULT NULL,
	`PRIX_VENTE_NET` varchar(255) DEFAULT NULL,
	`PRIXACHATAFACTURER` bit(1) DEFAULT NULL,
	`PRIXVENTECLIENT` bit(1) DEFAULT NULL,
	`PRODUIT` varchar(255) DEFAULT NULL,
	`PROGRAMME` varchar(255) DEFAULT NULL,
	`QTE_ACHAT` varchar(255) DEFAULT NULL,
	`QTE_VENTE` varchar(255) DEFAULT NULL,
	`REMARQUE` varchar(255) DEFAULT NULL,
	`REMISE_ACHAT` varchar(255) DEFAULT NULL,
	`REMISE_VENTE` varchar(255) DEFAULT NULL,
	`ST_ANOMALIE` bit(1) DEFAULT NULL,
	`ST_DECALAGE` bit(1) DEFAULT NULL,
	`ST_FACTURABLECLIENT` bit(1) DEFAULT NULL,
	`ST_FACTURABLEFOURNISSEUR` bit(1) DEFAULT NULL,
	`ST_MOTIFCOMMENTAIRE` bit(1) DEFAULT NULL,
	`ST_NEGOCIECLIENT` bit(1) DEFAULT NULL,
	`ST_NEGOCIEFOURNISSEUR` bit(1) DEFAULT NULL,
	`ST_OK` bit(1) DEFAULT NULL,
	`ST_PASSAGE` bit(1) DEFAULT NULL,
	`ST_PROGRAMME` bit(1) DEFAULT NULL,
	`ST_STANDBY` bit(1) DEFAULT NULL,
	`TOTAL_BRUT_ACHAT` varchar(255) DEFAULT NULL,
	`TOTAL_BRUT_VENTE` varchar(255) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_PLAN_MEDIA_WEB` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`ANNONCEUR` varchar(255) DEFAULT NULL,
	`BRUT_ACHAT` varchar(255) DEFAULT NULL,
	`BRUT_ACHAT_UNITAIRE` varchar(255) DEFAULT NULL,
	`BRUT_VENTE` varchar(255) DEFAULT NULL,
	`BRUT_VENTE_UNITAIRE` varchar(255) DEFAULT NULL,
	`CLIENT` varchar(255) DEFAULT NULL,
	`COMMISSSION_AGENCE` varchar(255) DEFAULT NULL,
	`COMPAGNE` varchar(255) DEFAULT NULL,
	`DATE_DEBUT` varchar(255) DEFAULT NULL,
	`DATE_FIN` varchar(255) DEFAULT NULL,
	`FORMAT` varchar(255) DEFAULT NULL,
	`INCIDENT` varchar(255) DEFAULT NULL,
	`MARGE_BRUT_MAA` varchar(255) DEFAULT NULL,
	`MESSAGE` varchar(255) DEFAULT NULL,
	`MONTANT_FACTURE_NET` varchar(255) DEFAULT NULL,
	`NBR_SEMAINE_JOUR` varchar(255) DEFAULT NULL,
	`NBR_SEMAINE_JOUR_S` varchar(255) DEFAULT NULL,
	`NET_ACHAT` varchar(255) DEFAULT NULL,
	`NET_VENTE` varchar(255) DEFAULT NULL,
	`NUM_BC_CLIENT` varchar(255) DEFAULT NULL,
	`NUM_BC_FORNISSEUR` varchar(255) DEFAULT NULL,
	`NUM_FACTURE_ACHAT` varchar(255) DEFAULT NULL,
	`PRIXACHATAFACTURER` bit(1) DEFAULT NULL,
	`PRIXVENTECLIENT` bit(1) DEFAULT NULL,
	`PRODUIT` varchar(255) DEFAULT NULL,
	`REMARQUE` varchar(255) DEFAULT NULL,
	`REMISE_ACHAT` varchar(255) DEFAULT NULL,
	`REMISE_VENTE` varchar(255) DEFAULT NULL,
	`SITE` varchar(255) DEFAULT NULL,
	`ST_ANOMALIE` bit(1) DEFAULT NULL,
	`ST_DECALAGE` bit(1) DEFAULT NULL,
	`ST_FACTURABLECLIENT` bit(1) DEFAULT NULL,
	`ST_FACTURABLEFOURNISSEUR` bit(1) DEFAULT NULL,
	`ST_MOTIFCOMMENTAIRE` bit(1) DEFAULT NULL,
	`ST_NEGOCIECLIENT` bit(1) DEFAULT NULL,
	`ST_NEGOCIEFOURNISSEUR` bit(1) DEFAULT NULL,
	`ST_OK` bit(1) DEFAULT NULL,
	`ST_PASSAGE` bit(1) DEFAULT NULL,
	`ST_PROGRAMME` bit(1) DEFAULT NULL,
	`ST_STANDBY` bit(1) DEFAULT NULL,
	`TOTAL_COM_AGENCE` varchar(255) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_PRODUIT` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`DESCRIPTION` longtext,
	`ID_COMMANDE` decimal(19,2) DEFAULT NULL,
	`PRIX_NEGOTIATION` decimal(18,2) DEFAULT NULL,
	`QUANTITE` varchar(20) DEFAULT NULL,
	`TOTALE` decimal(18,2) DEFAULT NULL,
	`TVA` decimal(18,2) DEFAULT NULL,
	`UNITE_PRIX` decimal(18,2) DEFAULT NULL,
	`ID_CLIENT` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_PRODUIT_CLIENT` (`ID_CLIENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_RAYON` (
	`CODE_RAYON` int(11) NOT NULL,
	`DESCRIPTION` varchar(45) DEFAULT NULL,
	`ID` bigint(20) NOT NULL,
	`ID_SECTEUR` decimal(19,2) DEFAULT NULL,
	`INTITULE` varchar(45) DEFAULT NULL,
	PRIMARY KEY (`CODE_RAYON`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_REGION` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`INTITULE` varchar(45) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_RELANCE_CLIENT` (
	`ID_RELANCE` bigint(20) NOT NULL AUTO_INCREMENT,
	`COMMENTAIRE` varchar(50) DEFAULT NULL,
	`DATE_RAPPEL` date DEFAULT NULL,
	`DATE_RELANCE` date DEFAULT NULL,
	`ID_FACTURE` bigint(20) DEFAULT NULL,
	`ID_STATUT_RELANCE` int(11) DEFAULT NULL,
	`ID_TYPE_RELANCE` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID_RELANCE`),
	KEY `BIZ_FK_RELANCE_CLIENT_FACTURE` (`ID_FACTURE`),
	KEY `BIZ_FK_RELANCE_CLIENT_STATUS_RELANCE` (`ID_STATUT_RELANCE`),
	KEY `BIZ_FK_RELANCE_CLIENT_TYPE` (`ID_TYPE_RELANCE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_REUNION` (
	`REUNION_ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`CONDUIT_PAR` varchar(50) DEFAULT NULL,
	`TYPE` varchar(50) DEFAULT NULL,
	`COMPTE_ID` int(11) DEFAULT NULL,
	`ID_STATUT_REUNION` int(11) DEFAULT NULL,
	PRIMARY KEY (`REUNION_ID`),
	KEY `BIZ_FK_REUNION_COMPTE` (`COMPTE_ID`),
	KEY `BIZ_FK_REUNION_STATUS` (`ID_STATUT_REUNION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_RH_AD_RECRUITMENT` (
	`BIZ_AD_RECRUITMENT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`BIZ_AD_TITLE` varchar(45) DEFAULT NULL,
	`BIZ_CONTRACT_TYPE` varchar(45) DEFAULT NULL,
	`BIZ_CREATION_DATE` date DEFAULT NULL,
	`BIZ_END_DATE` date DEFAULT NULL,
	`BIZ_JOB_LOCATION` varchar(45) DEFAULT NULL,
	`BIZ_JOB_NUMBER` varchar(45) DEFAULT NULL,
	`BIZ_PASSAGE_DATE` date DEFAULT NULL,
	`BIZ_REFERENCE` varchar(45) DEFAULT NULL,
	`BIZ_TITLE` varchar(45) DEFAULT NULL,
	PRIMARY KEY (`BIZ_AD_RECRUITMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_RH_RECRUITMENT_ORGANISM` (
	`BIZ_RH_RECRUITMENT_ORGANISM_ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`BIZ_ADDRESS` varchar(50) DEFAULT NULL,
	`BIZ_CONTACT` varchar(50) DEFAULT NULL,
	`BIZ_DENOMINATION` varchar(50) DEFAULT NULL,
	`BIZ_SITE` varchar(50) DEFAULT NULL,
	`BIZ_TEL` varchar(14) DEFAULT NULL,
	PRIMARY KEY (`BIZ_RH_RECRUITMENT_ORGANISM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_RUBRIQUE_FACTURE` (
	`ID_RUBRIQUE` int(11) NOT NULL AUTO_INCREMENT,
	`CODE` varchar(50) DEFAULT NULL,
	`DESIGNATION` varchar(50) DEFAULT NULL,
	`DEVISE` int(11) DEFAULT NULL,
	`MONTANT` decimal(18,2) DEFAULT NULL,
	`NET_A_PAYER` decimal(18,2) DEFAULT NULL,
	`PRIX_UNITAIRE_HT` decimal(18,2) DEFAULT NULL,
	`QUANTITE` int(11) DEFAULT NULL,
	`REMISE` decimal(2,2) DEFAULT NULL,
	`REMISE_HT` decimal(18,2) DEFAULT NULL,
	`TVA` decimal(18,2) DEFAULT NULL,
	`ID_FACTURE` bigint(20) DEFAULT NULL,
	PRIMARY KEY (`ID_RUBRIQUE`),
	KEY `BIZ_FK_RUBRIQUE_FACTURE` (`ID_FACTURE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_SECTEUR` (
	`CODE_SECTEUR` int(11) NOT NULL,
	`DESCRIPTION` varchar(45) DEFAULT NULL,
	`ID_IW_FILE` varchar(45) DEFAULT NULL,
	`INTITULE` varchar(45) DEFAULT NULL,
	`NOM_IMAGE` varchar(45) DEFAULT NULL,
	PRIMARY KEY (`CODE_SECTEUR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_SECTEUR_RAYON` (
	`ID` int(11) NOT NULL,
	`RAYON` int(11) DEFAULT NULL,
	`SECTEUR` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_RAYON` (`RAYON`),
	KEY `BIZ_FK_SECTEUR` (`SECTEUR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_SOCIETE` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`DATE_DEBUT` date DEFAULT NULL,
	`DATE_FIN` date DEFAULT NULL,
	`DESCRIPTION` varchar(50) DEFAULT NULL,
	`INTITULE` varchar(50) DEFAULT NULL,
	`SOCIETE_STATUT` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_SOUS_FAMILLE` (
	`CODE_SOUS_FAMILLE` varchar(50) NOT NULL,
	`DATE_MODIF` varchar(250) DEFAULT NULL,
	`INTITULE` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`CODE_SOUS_FAMILLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_SOUS_LIGNE_COMMANDE` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`CONFIRMATION_CLIENT` bit(1) DEFAULT NULL,
	`DATE` date DEFAULT NULL,
	`DATE_ENLEVEMENT_REELLE` date DEFAULT NULL,
	`DATE_ENLEVEMENT_SOUHAITEE` date DEFAULT NULL,
	`DATE_ENLEVEMENT_VALIDEE` date DEFAULT NULL,
	`DESCRIPTION` varchar(50) DEFAULT NULL,
	`LIEU_DECHARGEMENT` varchar(50) DEFAULT NULL,
	`LIEU_ENLEVEMENT` varchar(50) DEFAULT NULL,
	`QUANTITE` decimal(19,2) DEFAULT NULL,
	`STATUT` varchar(50) DEFAULT NULL,
	`ID_LINE_COMMANDE` bigint(20) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_SOUS_LIGNE_COMMANDE_PARENT` (`ID_LINE_COMMANDE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_SPOT` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`DATE_PASSAGE` date DEFAULT NULL,
	`DATE_PLANIFIE` date DEFAULT NULL,
	`DESCRIPTION` varchar(50) DEFAULT NULL,
	`DUREE_MIN` decimal(19,2) DEFAULT NULL,
	`EMAIL` varchar(50) DEFAULT NULL,
	`HEURE_PASSATION` varchar(50) DEFAULT NULL,
	`HOURE_PLANIFIE` varchar(50) DEFAULT NULL,
	`IW_EXEMPTION_STATUS` varchar(50) DEFAULT NULL,
	`STATUT` varchar(50) DEFAULT NULL,
	`ID_TRANCHE_HORAIRE` int(11) DEFAULT NULL,
	`PLAN_MEDIA` bigint(20) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_SPOT_HORAIRE` (`ID_TRANCHE_HORAIRE`),
	KEY `BIZ_FK_SPOT_PLAN_MEDIA` (`PLAN_MEDIA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_SRF_SOUS_FAMILLE` (
	`ID` int(11) NOT NULL,
	`SOUS_FAMILLE` varchar(50) DEFAULT NULL,
	`SECTEUR_RAYON_FAMILLE` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_SECTEUR_RAYON_FAMILLE` (`SECTEUR_RAYON_FAMILLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_SR_FAMILLE` (
	`ID` int(11) NOT NULL,
	`FAMILLE` int(11) DEFAULT NULL,
	`SECTEUR_RAYON` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_SR_FAMILLE` (`FAMILLE`),
	KEY `BIZ_FK_SR_SECTEUR_RAYON` (`SECTEUR_RAYON`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_STATUT_FACTURE` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`STATUT` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_STATUT_RELANCE` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`INTITULE_STATUT_RELANCE` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_STATUT_REUNION` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`INTITULE` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_TRANCHE_HORAIRE` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`DESCRIPTION` longtext,
	`INTITULE` varchar(5) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_TRESO_PLAN_TRESORIE` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`ANNER` int(11) DEFAULT NULL,
	`DATE_CREATION` date DEFAULT NULL,
	`INTITULE` varchar(50) DEFAULT NULL,
	`MOIS` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_TRESO_RUBRIQUE` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`AFFICHER_CHAMPS` varchar(50) DEFAULT NULL,
	`CREATEUR` varchar(50) DEFAULT NULL,
	`DATE_CREATION` date DEFAULT NULL,
	`INTITULE` varchar(50) DEFAULT NULL,
	`RUBRIQUE` int(11) DEFAULT NULL,
	`SOUS_RUBRIQUE` int(11) DEFAULT NULL,
	`TITRE` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_TRESO_SR_PAR_PLAN` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`DATEMODIFICATION` date DEFAULT NULL,
	`VALEUR` decimal(18,2) DEFAULT NULL,
	`ID_PLAN` int(11) DEFAULT NULL,
	`ID_RUBIQUE` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_TRESO_PLAN` (`ID_PLAN`),
	KEY `BIZ_FK_TRESO_RUBRIQUE` (`ID_RUBIQUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_TYPE_COMPTE` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`INTITULE` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_TYPE_CONTRAT` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`DESCRIPTION` longtext,
	`INTITULE` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_TYPE_PANNEAU` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`INTITULE` varchar(45) DEFAULT NULL,
	`TYPE_PANNEAU` varchar(45) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_TYPE_RELANCE` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`INTITULE_TYPE_RELANCE` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_WILAYA` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`INTITULE` varchar(45) DEFAULT NULL,
	`ID_REGION` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_WILAYA_REGION` (`ID_REGION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `SOUS_TRAITANT_INSTALLATEUR` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`DENOMINATION` varchar(45) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `ORG_ENTITE_ORGANISATIONNELLE` (
	`ENTITE_ORGANISATIONNELLE_ID` int(11) NOT NULL AUTO_INCREMENT,
	`ACT_ID_GROUPE` varchar(64) DEFAULT NULL,
	`ID_RESPONSABLE` int(11) DEFAULT NULL,
	`NOM_ENTITE` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`ENTITE_ORGANISATIONNELLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `ADM_G50` (
	`ID_G50` bigint(20) NOT NULL AUTO_INCREMENT,
	`IRG_SALAIRE` decimal(18,2) DEFAULT NULL,
	`IRG_TEMPORAIRE` decimal(18,2) DEFAULT NULL,
	`PRE_COMPTE` decimal(19,2) DEFAULT NULL,
	`TAP` decimal(19,2) DEFAULT NULL,
	`TAX_PUBLICATION` decimal(18,2) DEFAULT NULL,
	`TVA_17` decimal(18,2) DEFAULT NULL,
	`VAT_10` decimal(18,2) DEFAULT NULL,
	`VAT_17` decimal(18,2) DEFAULT NULL,
	PRIMARY KEY (`ID_G50`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
