ALTER TABLE `APC`
	ADD CONSTRAINT `APC_FK_COMMUNE` FOREIGN KEY (`ID_COMMUNE`) REFERENCES `APC` (`ID`);

ALTER TABLE `IW_BOOKING`
	ADD CONSTRAINT `IW_FK_BOOKING_RESOURCE` FOREIGN KEY (`IW_RESOURCE_ID`) REFERENCES `IW_RESOURCE` (`ID_RESOURCE`);

ALTER TABLE `IW_EVENT`
	ADD CONSTRAINT `IW_FK_EVENT_TYPE` FOREIGN KEY (`IW_EVENT_TYPE`) REFERENCES `IW_EVENT_TYPE` (`IW_EVENT_TYPE_ID`);

ALTER TABLE `IW_FILE`
	ADD CONSTRAINT `IW_FK_FILE_UPLOAD` FOREIGN KEY (`IW_UPLOAD`) REFERENCES `IW_UPLOAD` (`IW_UPLOAD_ID`);

ALTER TABLE `IW_INPUT`
	ADD CONSTRAINT `IW_FK_INPUT_FORM` FOREIGN KEY (`IW_FORM`) REFERENCES `IW_FORM` (`IW_FORM_ID`),
	ADD CONSTRAINT `IW_FK_INPUT_VARIABLE_PROCESS` FOREIGN KEY (`IW_VARIABLE_PROCESS`) REFERENCES `IW_VARIABLE_PROCESS` (`IW_VARIABLE_PROCESS_ID`);

ALTER TABLE `IW_LIST_OPTIONS`
	ADD CONSTRAINT `IW_PK_OPTIONS_LIST` FOREIGN KEY (`IW_LIST_ID`) REFERENCES `IW_LIST` (`IW_LIST_ID`);

ALTER TABLE `IW_LIST_TEST`
	ADD CONSTRAINT `IW_FK_LIST` FOREIGN KEY (`IWLISTID`) REFERENCES `IW_LIST` (`IW_LIST_ID`);

ALTER TABLE `IW_LOAN`
	ADD CONSTRAINT `IW_LOAN_CAR` FOREIGN KEY (`IW_CAR`) REFERENCES `IW_CAR` (`IW_CAR_ID`);

ALTER TABLE `IW_MULTILINE_ENTITY_FIELD`
	ADD CONSTRAINT `IW_FK_FIELD_LIST` FOREIGN KEY (`IW_LIST`) REFERENCES `IW_LIST` (`IW_LIST_ID`),
	ADD CONSTRAINT `IW_FK_MULTILINE_ENTITY` FOREIGN KEY (`IW_MULTILINE_ENTITY`) REFERENCES `IW_MULTILINE_ENTITY` (`IW_MULTILINE_ENTITY_ID`);

ALTER TABLE `IW_PROGRESS`
	ADD CONSTRAINT `IW_FK_PROGRESS_PHASE` FOREIGN KEY (`IW_PHASE`) REFERENCES `IW_PHASE` (`IW_PHASE_ID`);

ALTER TABLE `IW_RESOURCE`
	ADD CONSTRAINT `IW_FK_RESOURCE` FOREIGN KEY (`IW_ENTITY_NAME`) REFERENCES `IW_RESOURCE_TYPE` (`RESOURCE_TYPE_ID`);

ALTER TABLE `IW_VARIABLE_PROCESS`
	ADD CONSTRAINT `IW_VARIABLE_PROCESS_INPUT` FOREIGN KEY (`IW_INPUT`) REFERENCES `IW_INPUT` (`IW_INPUT_ID`);

ALTER TABLE `BIZ_AD_RECRUITMENT_PER_ORGANISM_RECRUITMENT`
	ADD CONSTRAINT `BIZ_FK_ORGAN` FOREIGN KEY (`BIZ_RGANISM_RECRUITMENT_ID`) REFERENCES `BIZ_RH_RECRUITMENT_ORGANISM` (`BIZ_RH_RECRUITMENT_ORGANISM_ID`),
	ADD CONSTRAINT `BIZ_FK_RECRU` FOREIGN KEY (`BIZ_AD_RECRUITMENT_ID`) REFERENCES `BIZ_CONDIDATE_PER_AD_RECRUITMENT` (`BIZ_CONDIDATE_PER_AD_RECRUITMENT_ID`);

ALTER TABLE `BIZ_AFFAIRE`
	ADD CONSTRAINT `BIZ_FK_AFFAIRE_DEVISE` FOREIGN KEY (`ID_DEVISE`) REFERENCES `BIZ_DEVISE` (`ID`);

ALTER TABLE `BIZ_APPEL`
	ADD CONSTRAINT `BIZ_FK_APPEL_COMPTE` FOREIGN KEY (`ID_COMPTE`) REFERENCES `BIZ_CLIENT` (`ID`),
	ADD CONSTRAINT `BIZ_FK_APPEL_STATUT_REUNION` FOREIGN KEY (`ID_STATUT_REUNION`) REFERENCES `BIZ_STATUT_REUNION` (`ID`);

ALTER TABLE `BIZ_ARTICLE`
	ADD CONSTRAINT `BIZ_FK_ARTICLE_SOUS_FAMILLE` FOREIGN KEY (`AR_SF_ID`) REFERENCES `BIZ_SOUS_FAMILLE` (`CODE_SOUS_FAMILLE`);

ALTER TABLE `BIZ_CLIENT`
	ADD CONSTRAINT `BIZ_UK_CLIENT_MAIL` FOREIGN KEY (`ID_MAIL`) REFERENCES `BIZ_MAIL` (`ID`),
	ADD CONSTRAINT `BIZ_FK_CLIENT_AFFAIRE` FOREIGN KEY (`ID_AFFAIRE`) REFERENCES `BIZ_AFFAIRE` (`ID`);

ALTER TABLE `BIZ_COMMUNE`
	ADD CONSTRAINT `BIZ_FK_COMMUNE_WILAYA` FOREIGN KEY (`ID_WILAYA`) REFERENCES `BIZ_WILAYA` (`ID`);

ALTER TABLE `BIZ_CONDIDATE_PER_AD_RECRUITMENT`
	ADD CONSTRAINT `BIZ_FK_RECRUTEMENT` FOREIGN KEY (`BIZ_AD_RECRUITMENT`) REFERENCES `BIZ_RH_AD_RECRUITMENT` (`BIZ_AD_RECRUITMENT_ID`),
	ADD CONSTRAINT `BIZ_FK_CANDIDATE` FOREIGN KEY (`BIZ_CONDIDATE_ID`) REFERENCES `BIZ_CONDIDATE_PER_AD_RECRUITMENT` (`BIZ_CONDIDATE_PER_AD_RECRUITMENT_ID`);

ALTER TABLE `BIZ_CONTACTS`
	ADD CONSTRAINT `BIZ_FK_CONTACTS_CLIENT` FOREIGN KEY (`ID_CLIENT`) REFERENCES `BIZ_CLIENT` (`ID_MAIL`);

ALTER TABLE `BIZ_CONTRAT`
	ADD CONSTRAINT `BIZ_FK_CONTRAT_TYPE` FOREIGN KEY (`ID_TYPE_CONTRAT`) REFERENCES `BIZ_TYPE_CONTRAT` (`ID`),
	ADD CONSTRAINT `BIZ_FK_CONTRAT_CLIENT` FOREIGN KEY (`ID_CLIENT`) REFERENCES `BIZ_CLIENT` (`ID`);

ALTER TABLE `BIZ_COURRIER_RECOUVREMENT`
	ADD CONSTRAINT `BIZ_FK_COURRIER_RECOUVREMENT_FACTURE` FOREIGN KEY (`ID_FACTURE`) REFERENCES `BIZ_FACTURE` (`ID_FACTURE`);

ALTER TABLE `BIZ_DOCUMENT_CLIENT`
	ADD CONSTRAINT `BIZ_FK_DOCUMENT_COMPTE` FOREIGN KEY (`ID_COMPTE`) REFERENCES `BIZ_CLIENT` (`ID`),
	ADD CONSTRAINT `BIZ_FK_DOCUMENT_CATEGORIE` FOREIGN KEY (`ID_CATEGORIE`) REFERENCES `BIZ_CATEGORIE_DOCUMENT` (`ID`);

ALTER TABLE `BIZ_ECHEANCE_PAIEMENT`
	ADD CONSTRAINT `BIZ_FK_PAIEMENT_FACTURE` FOREIGN KEY (`ID_FACTURE`) REFERENCES `BIZ_FACTURE` (`ID_FACTURE`);

ALTER TABLE `BIZ_EMPLACEMENT`
	ADD CONSTRAINT `BIZ_FK_EMPLACEMENT_TYPE` FOREIGN KEY (`ID_TYPE_PANNEAU`) REFERENCES `BIZ_TYPE_PANNEAU` (`ID`),
	ADD CONSTRAINT `BIZ_FK_EMPLACEMENT_SOUS_TRAITANT` FOREIGN KEY (`ID_SOUS_TRAITAN_INSTALATEUR`) REFERENCES `SOUS_TRAITANT_INSTALLATEUR` (`ID`),
	ADD CONSTRAINT `BIZ_FK_EMPLACEMENT_FACE_PANNEAU` FOREIGN KEY (`ID_FACE_PANNEAU`) REFERENCES `BIZ_FACE_PANNEAU` (`FACE_PANNEAU`),
	ADD CONSTRAINT `BIZ_FK_EMPLACEMENT_MODELE_PANNEAU` FOREIGN KEY (`ID_MODELE_panneau`) REFERENCES `BIZ_MODELE_PANNEAU` (`ID`),
	ADD CONSTRAINT `BIZ_FK_EMPLACEMENT_CONTRAT` FOREIGN KEY (`ID_CONTRAT_EMPLACEMENT`) REFERENCES `BIZ_CONTRAT_EMPLACEMENT` (`ID`),
	ADD CONSTRAINT `BIZ_FK_EMPLACEMENT_CATEGORIE` FOREIGN KEY (`ID_CATEGORIE_PANNEAU`) REFERENCES `BIZ_CATEGORIE_PANNEAU` (`ID`),
	ADD CONSTRAINT `BIZ_FK_EMPLACEMENT_PHOTO` FOREIGN KEY (`ID_PHOTO_EMPLACEMENT`) REFERENCES `BIZ_PHOTO_EMPLACEMENT` (`ID`),
	ADD CONSTRAINT `BIZ_FK_EMPLACEMENT_DATE_POSE` FOREIGN KEY (`ID_DATE_POSE`) REFERENCES `BIZ_DATE_POSE` (`ID`);

ALTER TABLE `BIZ_FACTURE`
	ADD CONSTRAINT `BIZ_FK_FACTURE_MODE_REGLEMENT` FOREIGN KEY (`MODE_REGLEMENT`) REFERENCES `BIZ_MODE_REGLEMENT` (`ID_MODE_REGLEMENT`),
	ADD CONSTRAINT `BIZ_FK_FACTURE_STATUT_FACTURE` FOREIGN KEY (`STATUT_FACTURE`) REFERENCES `BIZ_STATUT_FACTURE` (`ID`);

ALTER TABLE `BIZ_LIGNE_COMMANDE`
	ADD CONSTRAINT `BIZ_FK_LIGNE_COMMANDE_ARTICLE` FOREIGN KEY (`ID_ARTICLE`) REFERENCES `BIZ_ARTICLE` (`AR_ID`),
	ADD CONSTRAINT `BIZ_FK_LIGNE_COMMANDE_COMMAND` FOREIGN KEY (`ID_COMMAND`) REFERENCES `BIZ_COMMANDE` (`COMMAND_ID`),
	ADD CONSTRAINT `BIZ_FK_LIGNE_COMMANDE_FAMILLE` FOREIGN KEY (`ID_FAMILLE`) REFERENCES `BIZ_FAMILLE` (`CODE_FAMILLE`);

ALTER TABLE `BIZ_LIGNE_FOURNISSEUR`
	ADD CONSTRAINT `BIZ_FK_LIGNE_FOURNISSEUR_COMMAND` FOREIGN KEY (`ID_COMMAND`) REFERENCES `BIZ_COMMANDE` (`COMMAND_ID`),
	ADD CONSTRAINT `BIZ_FK_LIGNE_FOURNISSEUR_FOURNISSEUR` FOREIGN KEY (`ID_FOURNISSEUR`) REFERENCES `BIZ_FOURNISSEUR` (`ID`);

ALTER TABLE `BIZ_MAGASIN`
	ADD CONSTRAINT `BIZ_FK_MAGASIN_SECTEUR` FOREIGN KEY (`SECTEUR`) REFERENCES `BIZ_SECTEUR` (`CODE_SECTEUR`);

ALTER TABLE `BIZ_MAIL`
	ADD CONSTRAINT `BIZ_FK_MAIL_MODELE` FOREIGN KEY (`ID_MODELE_MAIL`) REFERENCES `BIZ_MODELE_MAIL` (`Id`);

ALTER TABLE `BIZ_PLAN_MEDIA`
	ADD CONSTRAINT `BIZ_FK_PLAN_MEDIA_FACTURE` FOREIGN KEY (`ID_FACTURE`) REFERENCES `BIZ_FACTURE` (`ID_FACTURE`),
	ADD CONSTRAINT `BIZ_FK_PLAN_MEDIA_COMPAGNIE` FOREIGN KEY (`ID_COMPAGNIE`) REFERENCES `BIZ_CAMPAGNE` (`ID`),
	ADD CONSTRAINT `BIZ_FK_PLAN_MEDIA_PRODUIT` FOREIGN KEY (`ID_PRODUIT`) REFERENCES `BIZ_PRODUIT` (`ID`);

ALTER TABLE `BIZ_PRODUIT`
	ADD CONSTRAINT `BIZ_FK_PRODUIT_CLIENT` FOREIGN KEY (`ID_CLIENT`) REFERENCES `BIZ_CLIENT` (`ID`);

ALTER TABLE `BIZ_RELANCE_CLIENT`
	ADD CONSTRAINT `BIZ_FK_RELANCE_CLIENT_STATUS_RELANCE` FOREIGN KEY (`ID_STATUT_RELANCE`) REFERENCES `BIZ_STATUT_RELANCE` (`ID`),
	ADD CONSTRAINT `BIZ_FK_RELANCE_CLIENT_TYPE` FOREIGN KEY (`ID_TYPE_RELANCE`) REFERENCES `BIZ_TYPE_RELANCE` (`ID`),
	ADD CONSTRAINT `BIZ_FK_RELANCE_CLIENT_FACTURE` FOREIGN KEY (`ID_FACTURE`) REFERENCES `BIZ_FACTURE` (`ID_FACTURE`);

ALTER TABLE `BIZ_REUNION`
	ADD CONSTRAINT `BIZ_FK_REUNION_STATUS` FOREIGN KEY (`ID_STATUT_REUNION`) REFERENCES `BIZ_STATUT_REUNION` (`ID`),
	ADD CONSTRAINT `BIZ_FK_REUNION_COMPTE` FOREIGN KEY (`COMPTE_ID`) REFERENCES `BIZ_CLIENT` (`ID`);

ALTER TABLE `BIZ_RUBRIQUE_FACTURE`
	ADD CONSTRAINT `BIZ_FK_RUBRIQUE_FACTURE` FOREIGN KEY (`ID_FACTURE`) REFERENCES `BIZ_FACTURE` (`ID_FACTURE`);

ALTER TABLE `BIZ_SECTEUR_RAYON`
	ADD CONSTRAINT `BIZ_FK_RAYON` FOREIGN KEY (`RAYON`) REFERENCES `BIZ_RAYON` (`CODE_RAYON`),
	ADD CONSTRAINT `BIZ_FK_SECTEUR` FOREIGN KEY (`SECTEUR`) REFERENCES `BIZ_SECTEUR` (`CODE_SECTEUR`);

ALTER TABLE `BIZ_SOUS_LIGNE_COMMANDE`
	ADD CONSTRAINT `BIZ_FK_SOUS_LIGNE_COMMANDE_PARENT` FOREIGN KEY (`ID_LINE_COMMANDE`) REFERENCES `BIZ_LIGNE_COMMANDE` (`ID`);

ALTER TABLE `BIZ_SPOT`
	ADD CONSTRAINT `BIZ_FK_SPOT_HORAIRE` FOREIGN KEY (`ID_TRANCHE_HORAIRE`) REFERENCES `BIZ_TRANCHE_HORAIRE` (`ID`),
	ADD CONSTRAINT `BIZ_FK_SPOT_PLAN_MEDIA` FOREIGN KEY (`PLAN_MEDIA`) REFERENCES `BIZ_PLAN_MEDIA` (`ID`);

ALTER TABLE `BIZ_SRF_SOUS_FAMILLE`
	ADD CONSTRAINT `BIZ_FK_SECTEUR_RAYON_FAMILLE` FOREIGN KEY (`SECTEUR_RAYON_FAMILLE`) REFERENCES `BIZ_SR_FAMILLE` (`ID`);

ALTER TABLE `BIZ_SR_FAMILLE`
	ADD CONSTRAINT `BIZ_FK_SR_FAMILLE` FOREIGN KEY (`FAMILLE`) REFERENCES `BIZ_FAMILLE` (`CODE_FAMILLE`),
	ADD CONSTRAINT `BIZ_FK_SR_SECTEUR_RAYON` FOREIGN KEY (`SECTEUR_RAYON`) REFERENCES `BIZ_SECTEUR_RAYON` (`ID`);

ALTER TABLE `BIZ_TRESO_SR_PAR_PLAN`
	ADD CONSTRAINT `BIZ_FK_TRESO_RUBRIQUE` FOREIGN KEY (`ID_RUBIQUE`) REFERENCES `BIZ_TRESO_RUBRIQUE` (`ID`),
	ADD CONSTRAINT `BIZ_FK_TRESO_PLAN` FOREIGN KEY (`ID_PLAN`) REFERENCES `BIZ_TRESO_PLAN_TRESORIE` (`ID`);

ALTER TABLE `BIZ_WILAYA`
	ADD CONSTRAINT `BIZ_FK_WILAYA_REGION` FOREIGN KEY (`ID_REGION`) REFERENCES `BIZ_REGION` (`ID`);

