LOCK TABLES `ACT_ID_USER` WRITE;
INSERT INTO `ACT_ID_USER` (`ID_`, `REV_`, `FIRST_`, `LAST_`, `EMAIL_`, `PWD_`, `PICTURE_ID_`) VALUES ('admin','1','Administrateur','ImagineWorkflow','no-reply@imaginepatners.com','$2a$11$FciA2vtZazSQDZM3PJmihelaYR8I.QR0oRwSbNHYSm7tiN7C.4stW',NULL);
INSERT INTO `ACT_ID_USER` (`ID_`, `REV_`, `FIRST_`, `LAST_`, `EMAIL_`, `PWD_`, `PICTURE_ID_`) VALUES ('superadmin','1','Rescue','User','no-reply@imaginepatners.com',NULL,NULL);
UNLOCK TABLES;

LOCK TABLES `IW_USER_DETAILS` WRITE;
INSERT INTO `IW_USER_DETAILS` (`IW_USER_DETAILS_ID`, `IW_ACT_ID_USER`, `IW_ACTIVE`, `IW_GENERATED_PASSWORD_PLAIN`, `IW_PASSWORD_CHANGE_DATE`, `IW_TYPE_AUTHENTIFICATION`) VALUES (1,'superadmin',0x01,NULL,NULL,'rescue');
INSERT INTO `IW_USER_DETAILS` (`IW_USER_DETAILS_ID`, `IW_ACT_ID_USER`, `IW_ACTIVE`, `IW_GENERATED_PASSWORD_PLAIN`, `IW_PASSWORD_CHANGE_DATE`, `IW_TYPE_AUTHENTIFICATION`) VALUES (2,'admin',0x01,NULL,NULL,'db');
UNLOCK TABLES;
