LOCK TABLES `ACT_ID_GROUP` WRITE;
INSERT INTO `ACT_ID_GROUP` (`ID_`, `REV_`, `NAME_`, `TYPE_`) VALUES ('ROLE_ADMIN',1,'Admin','admin');
INSERT INTO `ACT_ID_GROUP` (`ID_`, `REV_`, `NAME_`, `TYPE_`) VALUES ('ROLE_SUPER_ADMIN',1,'Super Administrateur (Développeur)','admin');
INSERT INTO `ACT_ID_GROUP` (`ID_`, `REV_`, `NAME_`, `TYPE_`) VALUES ('ROLE_USER',1,'Utilisateur','user');
UNLOCK TABLES;

LOCK TABLES `IW_GROUP_DETAILS` WRITE;
INSERT INTO `IW_GROUP_DETAILS` (`IW_GROUP_DETAILS_ID`, `IW_ACTIVE`, `IW_GROUP`, `IW_RESPONSIBLE`, `IW_TYPE`, `IW_VISIBALE`) VALUES (1,0x01,'ROLE_ADMIN',NULL,'functional',0x01);
INSERT INTO `IW_GROUP_DETAILS` (`IW_GROUP_DETAILS_ID`, `IW_ACTIVE`, `IW_GROUP`, `IW_RESPONSIBLE`, `IW_TYPE`, `IW_VISIBALE`) VALUES (2,0x01,'ROLE_SUPER_ADMIN',NULL,'functional',0x00);
INSERT INTO `IW_GROUP_DETAILS` (`IW_GROUP_DETAILS_ID`, `IW_ACTIVE`, `IW_GROUP`, `IW_RESPONSIBLE`, `IW_TYPE`, `IW_VISIBALE`) VALUES (3,0x01,'ROLE_USER',NULL,'functional',0x00);
UNLOCK TABLES;
