LOCK TABLES `ACT_ID_MEMBERSHIP` WRITE;
INSERT INTO `ACT_ID_MEMBERSHIP` (`USER_ID_`, `GROUP_ID_`) VALUES ('admin','ROLE_SUPER_ADMIN');
INSERT INTO `ACT_ID_MEMBERSHIP` (`USER_ID_`, `GROUP_ID_`) VALUES ('admin','ROLE_ADMIN');
INSERT INTO `ACT_ID_MEMBERSHIP` (`USER_ID_`, `GROUP_ID_`) VALUES ('admin','ROLE_USER');
INSERT INTO `ACT_ID_MEMBERSHIP` (`USER_ID_`, `GROUP_ID_`) VALUES ('superadmin','ROLE_SUPER_ADMIN');
INSERT INTO `ACT_ID_MEMBERSHIP` (`USER_ID_`, `GROUP_ID_`) VALUES ('superadmin','ROLE_USER');
UNLOCK TABLES;
