LOCK TABLES `IW_INPUT` WRITE;
ALTER TABLE `IW_INPUT`
	ADD COLUMN `IW_ALLOW_CREATE` tinyint(1) DEFAULT '0' AFTER `IW_INPUT_ID`,
	ADD COLUMN `IW_DELETE` tinyint(1) DEFAULT '0' AFTER `IW_DATE_FORMAT`,
	ADD COLUMN `IW_FILTER` tinyint(1) DEFAULT '0' AFTER `IW_INPUT_ID`,
	ADD COLUMN `IW_UPDATE` tinyint(1) DEFAULT '0' AFTER `IW_ENTITY_FILTER`;
UNLOCK TABLES;
