CREATE TABLE `IW_STANDALONE_TASK` (
	`IW_STANDALONE_TASK_ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`IW_APPLICATION_KEY` varchar(50) DEFAULT NULL,
	`IW_DESCRIPTION` longtext,
	`IW_FORM` bigint(20) DEFAULT NULL,
	`IW_NAME` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`IW_STANDALONE_TASK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
