LOCK TABLES `IW_USER_DETAILS` WRITE;
ALTER TABLE `IW_USER_DETAILS`
	ADD COLUMN `IW_VISIBLE` BIT(1) NOT NULL DEFAULT 1;

UPDATE `IW_USER_DETAILS` SET `IW_VISIBLE` = 0 WHERE `IW_ACT_ID_USER` IN ('superadmin');
UNLOCK TABLES;
