LOCK TABLES `IW_VARIABLE_PROCESS` WRITE;
ALTER TABLE `IW_VARIABLE_PROCESS`
	MODIFY `IW_INPUT` bigint(20) DEFAULT NULL,
	DROP FOREIGN KEY `IW_VARIABLE_PROCESS_INPUT`;
UNLOCK TABLES;

LOCK TABLES `IW_INPUT` WRITE;
ALTER TABLE `IW_INPUT`
	DROP PRIMARY KEY,
	ADD `IW_INPUT_REAL_ID` bigint(20) NOT NULL AUTO_INCREMENT,
	ADD PRIMARY KEY (`IW_INPUT_REAL_ID`);
UNLOCK TABLES;

LOCK TABLES `IW_VARIABLE_PROCESS` WRITE;
ALTER TABLE `IW_VARIABLE_PROCESS`
	ADD CONSTRAINT `IW_VARIABLE_PROCESS_INPUT` FOREIGN KEY (`IW_INPUT`) REFERENCES `IW_INPUT` (`IW_INPUT_REAL_ID`);
UNLOCK TABLES;
