LOCK TABLES `ORG_ENTITE_ORGANISATIONNELLE` WRITE;
ALTER TABLE `ORG_ENTITE_ORGANISATIONNELLE`
	ADD COLUMN `EMPLOYE_ID` int(11) DEFAULT NULL,
	ADD COLUMN `ID_ENTITE_ORGA_SUIV` int(11) DEFAULT NULL;

ALTER TABLE `ORG_ENTITE_ORGANISATIONNELLE`
	ADD INDEX `ORG_FK_PARENT` (`ID_ENTITE_ORGA_SUIV`),
	ADD CONSTRAINT `ORG_FK_PARENT` FOREIGN KEY (`ID_ENTITE_ORGA_SUIV`) REFERENCES `ORG_ENTITE_ORGANISATIONNELLE` (`ENTITE_ORGANISATIONNELLE_ID`);

INSERT INTO `ORG_ENTITE_ORGANISATIONNELLE` (`NOM_ENTITE`) VALUES ('Direction générale');
UNLOCK TABLES;
