LOCK TABLES `IW_GROUP_DETAILS` WRITE;
UPDATE `IW_GROUP_DETAILS` SET `IW_VISIBALE` = 1 WHERE `IW_VISIBALE` IS NULL;
ALTER TABLE `IW_GROUP_DETAILS` MODIFY COLUMN `IW_VISIBALE` TINYINT(1) NOT NULL DEFAULT 1;
UNLOCK TABLES;
