LOCK TABLES `BIZ_FOURNISSEUR` WRITE;
ALTER TABLE `BIZ_FOURNISSEUR`
	ADD COLUMN `CLASSEMENT_ACHAT` varchar(45) DEFAULT NULL AFTER `UK`,
	ADD COLUMN `CLASSEMENT_METIER` varchar(45) DEFAULT NULL AFTER `CLASSEMENT_ACHAT`,
	ADD COLUMN `CLASSEMENT_DEFINITIF` varchar(45) DEFAULT NULL AFTER `CLASSEMENT_METIER`,
	ADD COLUMN `OFFRE_FINANCIERE` bigint(20) DEFAULT NULL AFTER `CLASSEMENT_DEFINITIF`,
	ADD COLUMN `OFFRE_TECHNIQUE` bigint(20) DEFAULT NULL AFTER `OFFRE_FINANCIERE`;

ALTER TABLE `BIZ_FOURNISSEUR`
	ADD INDEX `FK_BIZ_FOURNISSEUR_IW_UPLOAD_OFFRE_FINANCIERE` (`OFFRE_FINANCIERE`),
	ADD INDEX `FK_BIZ_FOURNISSEUR_IW_UPLOAD_OFFRE_TECHNIQUE` (`OFFRE_TECHNIQUE`),
	ADD CONSTRAINT `FK_BIZ_FOURNISSEUR_IW_UPLOAD_OFFRE_FINANCIERE` FOREIGN KEY (`OFFRE_FINANCIERE`) REFERENCES `IW_UPLOAD` (`IW_UPLOAD_ID`),
	ADD CONSTRAINT `FK_BIZ_FOURNISSEUR_IW_UPLOAD_OFFRE_TECHNIQUE` FOREIGN KEY (`OFFRE_FINANCIERE`) REFERENCES `IW_UPLOAD` (`IW_UPLOAD_ID`);
UNLOCK TABLES;

LOCK TABLES `BIZ_LIGNE_COMMANDE` WRITE;
ALTER TABLE `BIZ_LIGNE_COMMANDE`
	ADD COLUMN `CODE_BUDGET` varchar(45) DEFAULT NULL AFTER `TVA`,
	ADD COLUMN `DEROGATION_BUDGET` varchar(45) DEFAULT NULL AFTER `CODE_BUDGET`,
	ADD COLUMN `VALIDATION_BUDGET` tinyint(1) DEFAULT '0' AFTER `DEROGATION_BUDGET`;
UNLOCK TABLES;
