CREATE TABLE `RH_SALAIRE_DU_MOIS` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`COLLABORATEUR_ID` int(11) NOT NULL,
	`AUGMENTATION` decimal(6,2) DEFAULT NULL,
	`PRIME_COMPENSATRICE` decimal(6,2) DEFAULT NULL,
	`AVANCE` decimal(6,2) DEFAULT NULL,
	`NBR_ABSENCE` int(11) DEFAULT NULL,
	`REMARQUE` text NOT NULL,
	`NET_A_PAYER` decimal(6,2) NOT NULL,
	`STATUS` varchar(50) NOT NULL,
	PRIMARY KEY (`ID`),
	KEY `RH_FK_SALAIRE_DU_MOIS_COLLABORATEUR` (`COLLABORATEUR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

LOCK TABLES `RH_SALAIRE_DU_MOIS` WRITE;
ALTER TABLE `RH_SALAIRE_DU_MOIS`
	ADD CONSTRAINT `RH_FK_SALAIRE_DU_MOIS_COLLABORATEUR` FOREIGN KEY (`COLLABORATEUR_ID`) REFERENCES `RH_COLLABORATEUR` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
UNLOCK TABLES;
