LOCK TABLES `IW_VARIABLE_PROCESS` WRITE;
ALTER TABLE `IW_VARIABLE_PROCESS` DROP FOREIGN KEY `IW_VARIABLE_PROCESS_INPUT`;
ALTER TABLE `IW_VARIABLE_PROCESS` ADD CONSTRAINT `IW_VARIABLE_PROCESS_INPUT` FOREIGN KEY (`IW_INPUT`) REFERENCES `IW_INPUT` (`IW_INPUT_REAL_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
UNLOCK TABLES;
