CREATE TABLE `IW_COLUMN_TASK` (
	`IW_COLUMN_TASK_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`IW_NAME` VARCHAR(45) DEFAULT NULL,
	`IW_COLUMN_KEY` VARCHAR(45) DEFAULT NULL,
	`IW_IS_COLUMN_HISTORIQUE` BIT(1) DEFAULT 0,
	PRIMARY KEY (`IW_COLUMN_TASK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

LOCK TABLES `IW_COLUMN_TASK` WRITE;
INSERT INTO `IW_COLUMN_TASK` (`IW_NAME`, `IW_COLUMN_KEY`, `IW_IS_COLUMN_HISTORIQUE`) VALUES ('Tâche', 'task_name', 0);
INSERT INTO `IW_COLUMN_TASK` (`IW_NAME`, `IW_COLUMN_KEY`, `IW_IS_COLUMN_HISTORIQUE`) VALUES ('Date de création', 'date_creation', 0);
INSERT INTO `IW_COLUMN_TASK` (`IW_NAME`, `IW_COLUMN_KEY`, `IW_IS_COLUMN_HISTORIQUE`) VALUES ('Processus', 'process_id', 0);
INSERT INTO `IW_COLUMN_TASK` (`IW_NAME`, `IW_COLUMN_KEY`, `IW_IS_COLUMN_HISTORIQUE`) VALUES ('N° tâche', 'task_id', 0);
UNLOCK TABLES;
