LOCK TABLES `IW_VARIABLE_PROCESS` WRITE;
ALTER TABLE `IW_VARIABLE_PROCESS`
	ADD COLUMN `IW_COLUMN_TASK` BIGINT(20) NULL AFTER `IW_INPUT`,
	ADD COLUMN `IW_COLUMN_SIZE` BIGINT(20) NULL AFTER `IW_COLUMN_TASK`,
	ADD INDEX `FK_IW_VARIABLE_IW_COLUMN_TASK` (`IW_COLUMN_TASK`),
	ADD CONSTRAINT `FK_IW_VARIABLE_IW_COLUMN_TASK` FOREIGN KEY (`IW_COLUMN_TASK`) REFERENCES `IW_COLUMN_TASK` (`IW_COLUMN_TASK_ID`);
UNLOCK TABLES;
