LOCK TABLES `IW_MULTILINE_ENTITY` WRITE;
DELETE FROM `IW_MULTILINE_ENTITY` WHERE `IW_CLASS` LIKE "com.imaginepartners.imagineworkflow.models.business.BizModelePanneau";
DELETE FROM `IW_MULTILINE_ENTITY` WHERE `IW_CLASS` LIKE "com.imaginepartners.imagineworkflow.models.business.BizEmplacement";
DELETE FROM `IW_MULTILINE_ENTITY` WHERE `IW_CLASS` LIKE "com.imaginepartners.imagineworkflow.models.business.BizPhotoEmplacement";
DELETE FROM `IW_MULTILINE_ENTITY` WHERE `IW_CLASS` LIKE "com.imaginepartners.imagineworkflow.models.business.BizCategoriePanneau";
DELETE FROM `IW_MULTILINE_ENTITY` WHERE `IW_CLASS` LIKE "com.imaginepartners.imagineworkflow.models.business.BizFacePanneau";
DELETE FROM `IW_MULTILINE_ENTITY` WHERE `IW_CLASS` LIKE "com.imaginepartners.imagineworkflow.models.business.BizModelePanneau";
DELETE FROM `IW_MULTILINE_ENTITY` WHERE `IW_CLASS` LIKE "com.imaginepartners.imagineworkflow.models.business.BizPlanMediaOoh";
DELETE FROM `IW_MULTILINE_ENTITY` WHERE `IW_CLASS` LIKE "com.imaginepartners.imagineworkflow.models.business.BizPlanMediaPress";
DELETE FROM `IW_MULTILINE_ENTITY` WHERE `IW_CLASS` LIKE "com.imaginepartners.imagineworkflow.models.business.BizPlanMediaRadio";
DELETE FROM `IW_MULTILINE_ENTITY` WHERE `IW_CLASS` LIKE "com.imaginepartners.imagineworkflow.models.business.BizPlanMediaTv";
DELETE FROM `IW_MULTILINE_ENTITY` WHERE `IW_CLASS` LIKE "com.imaginepartners.imagineworkflow.models.business.BizPlanMediaWeb";
DELETE FROM `IW_MULTILINE_ENTITY` WHERE `IW_CLASS` LIKE "com.imaginepartners.imagineworkflow.models.business.BizSpot";
DELETE FROM `IW_MULTILINE_ENTITY` WHERE `IW_CLASS` LIKE "com.imaginepartners.imagineworkflow.models.business.BizPlanMedia";
DELETE FROM `IW_MULTILINE_ENTITY` WHERE `IW_CLASS` LIKE "com.imaginepartners.imagineworkflow.models.business.BizTypePanneau";
DELETE FROM `IW_MULTILINE_ENTITY` WHERE `IW_CLASS` LIKE "com.imaginepartners.imagineworkflow.models.business.BizTrancheHoraire";
DELETE FROM `IW_MULTILINE_ENTITY` WHERE `IW_CLASS` LIKE "com.imaginepartners.imagineworkflow.models.business.BizContratEmplacement";
DELETE FROM `IW_MULTILINE_ENTITY` WHERE `IW_CLASS` LIKE "com.imaginepartners.imagineworkflow.models.business.BizDatePose";
DELETE FROM `IW_MULTILINE_ENTITY` WHERE `IW_CLASS` LIKE "com.imaginepartners.imagineworkflow.models.business.SousTraitantInstallateur";
UNLOCK TABLES;
