CREATE TABLE `IW_TREE` (
	`CHILD` INT NOT NULL AUTO_INCREMENT,
	`PARENT` INT NULL,
	`TITLE` VARCHAR(50) NULL,
	`DESCRIPTION` VARCHAR(500) NULL,
	PRIMARY KEY (`CHILD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

LOCK TABLES `IW_TREE` WRITE;
ALTER TABLE `IW_TREE`
	ADD INDEX `IW_FK_PARENT` (`PARENT`);
ALTER TABLE `IW_TREE`
	ADD CONSTRAINT `IW_FK_PARENT` FOREIGN KEY (`PARENT`) REFERENCES `IW_TREE` (`CHILD`);
UNLOCK TABLES;
