CREATE TABLE `BIZ_FOURNISSEUR_TYPE` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`INTITULE` VARCHAR(50) NULL,
	`DESCRIPTION` VARCHAR(500) NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

LOCK TABLES `BIZ_FOURNISSEUR` WRITE;
ALTER TABLE `BIZ_FOURNISSEUR`
	DROP COLUMN `TYPE_FOURNISSEUR`;
ALTER TABLE `BIZ_FOURNISSEUR`
	ADD COLUMN `TYPE_FOURNISSEUR` BIGINT(20) NULL,
	ADD INDEX `FK_BIZ_FOURNISSEUR_FOURNISSEUR_TYPE` (`TYPE_FOURNISSEUR`),
	ADD CONSTRAINT `FK_BIZ_FOURNISSEUR_FOURNISSEUR_TYPE` FOREIGN KEY (`TYPE_FOURNISSEUR`) REFERENCES `BIZ_FOURNISSEUR_TYPE` (`ID`);
UNLOCK TABLES;
