LOCK TABLES `BIZ_POLITIQUE_PRIX` WRITE;
INSERT INTO `BIZ_POLITIQUE_PRIX` (`TYPE_MAGASINS`, `TAUX_PRIX`) VALUES ('super', 5);
INSERT INTO `BIZ_POLITIQUE_PRIX` (`TYPE_MAGASINS`, `TAUX_PRIX`) VALUES ('proxy', 10);
INSERT INTO `BIZ_POLITIQUE_PRIX` (`TYPE_MAGASINS`, `TAUX_PRIX`) VALUES ('relai', 20);
UNLOCK TABLES;
