LOCK TABLES `BIZ_PRIX_VENTE` WRITE;
ALTER TABLE `BIZ_PRIX_VENTE`
	ADD COLUMN `PRIX_RETENU_TTC` DECIMAL(10,4) NULL DEFAULT NULL,
	CHANGE COLUMN `PRIX_HT` `PRIX_HT` DECIMAL(10,4) NULL DEFAULT NULL ,
	CHANGE COLUMN `PRIX_TTC` `PRIX_TTC` DECIMAL(10,4) NULL DEFAULT NULL;
UNLOCK TABLES;
