LOCK TABLES `IW_FORM_TEMPLATE` WRITE;
INSERT INTO `IW_FORM_TEMPLATE` (`IW_DESCRIPTION`, `IW_NAME`, `IW_VALUE`) VALUES ('TEMPLATE Politique de Prix', 'Politique de Prix', 'politiquePrix.xhtml');
UNLOCK TABLES;
