LOCK TABLES `RH_ANNONCE_RECRUTEMENT` WRITE;
ALTER TABLE `RH_ANNONCE_RECRUTEMENT`
	ADD COLUMN `ORGANISME` VARCHAR(255) NULL;
UNLOCK TABLES;

LOCK TABLES `IW_LIST` WRITE;
INSERT INTO `IW_LIST` (`IW_DESCIRPTION`, `IW_NAME`, `IW_POSTED_DATE`, `IW_TITLE`) VALUE ('', 'Organisme', '2016-06-05', NULL);
UNLOCK TABLES;

LOCK TABLES `IW_LIST_OPTIONS` WRITE;
SET @LIST_ID = LAST_INSERT_ID();
INSERT INTO `IW_LIST_OPTIONS` (`IW_DESCIRPTION`, `IW_NAME`, `IW_LIST_ID`) VALUE (NULL, 'ANEM', @LIST_ID);
INSERT INTO `IW_LIST_OPTIONS` (`IW_DESCIRPTION`, `IW_NAME`, `IW_LIST_ID`) VALUE (NULL, 'JOURNAUX', @LIST_ID);
INSERT INTO `IW_LIST_OPTIONS` (`IW_DESCIRPTION`, `IW_NAME`, `IW_LIST_ID`) VALUE (NULL, 'AUTRE', @LIST_ID);
UNLOCK TABLES;
