CREATE TABLE `BIZ_REGLEMENT` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`DATE_SAISIE`  DATE DEFAULT NULL,
	`DATE_JOUR`  DATE DEFAULT NULL,
	`MONTANT_REGLEMENT` DECIMAL(18,2) DEFAULT NULL,
	`DEVISE_REGLEMENT` int(11) NOT NULL,
	`DATE_VALEUR`  DATE DEFAULT NULL,
	`DERNIER_REGLEMENT` BIT(1) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

LOCK TABLES `BIZ_REGLEMENT` WRITE;
ALTER TABLE `BIZ_REGLEMENT`
	ADD INDEX `BIZ_FK_REGLEMENT_DEVISE_INDX` (`DEVISE_REGLEMENT`),
	ADD CONSTRAINT `BIZ_FK_REGLEMENT_DEVISE` FOREIGN KEY (`DEVISE_REGLEMENT`) REFERENCES `BIZ_DEVISE` (`ID`);

UNLOCK TABLES;
