ALTER TABLE `IW_INPUT` ADD `IW_INPUT_SIZE` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

ALTER TABLE `IW_INPUT` ADD `IW_DATE_PATTENRN` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
