LOCK TABLES `IW_BOOKING` WRITE;
	ALTER TABLE `IW_BOOKING` CHANGE `IW_ALL_DAY` `IW_ALL_DAY` TINYINT(1) NOT NULL;
UNLOCK TABLES;
LOCK TABLES `IW_COLUMN_TASK` WRITE;
	ALTER TABLE `IW_COLUMN_TASK` CHANGE `IW_IS_COLUMN_HISTORIQUE` `IW_IS_COLUMN_HISTORIQUE` TINYINT(1) NULL DEFAULT '0';
UNLOCK TABLES;
LOCK TABLES `IW_CONFIG` WRITE;
	ALTER TABLE `IW_CONFIG` CHANGE `CONFIG_EDITABLE` `CONFIG_EDITABLE` TINYINT(1) NULL DEFAULT NULL;
UNLOCK TABLES;
LOCK TABLES `IW_EVENT` WRITE;
	ALTER TABLE `IW_EVENT` CHANGE `IW_ALL_DAY` `IW_ALL_DAY` TINYINT(1) NULL DEFAULT NULL;
UNLOCK TABLES;
LOCK TABLES `IW_GROUP_DETAILS` WRITE;
	ALTER TABLE `IW_GROUP_DETAILS` CHANGE `IW_ACTIVE` `IW_ACTIVE` TINYINT(1) NULL DEFAULT NULL;
UNLOCK TABLES;
LOCK TABLES `IW_INPUT` WRITE;
	ALTER TABLE `IW_INPUT`
		CHANGE `IW_EDITABLE` `IW_EDITABLE` TINYINT(1) NULL DEFAULT NULL,
		CHANGE `IW_MULTIPLE` `IW_MULTIPLE` TINYINT(1) NULL DEFAULT NULL,
		CHANGE `IW_REQUIRED` `IW_REQUIRED` TINYINT(1) NULL DEFAULT NULL,
		CHANGE `IW_USE_REQUEST` `IW_USE_REQUEST` TINYINT(1) NULL DEFAULT NULL;
UNLOCK TABLES;
LOCK TABLES `IW_LICENSE` WRITE;
	ALTER TABLE `IW_LICENSE` CHANGE `IW_ACTIVE` `IW_ACTIVE` TINYINT(1) NULL DEFAULT NULL;
UNLOCK TABLES;
LOCK TABLES `IW_LOAN` WRITE;
	ALTER TABLE `IW_LOAN` CHANGE `IW_ALL_DAY` `IW_ALL_DAY` TINYINT(1) NOT NULL;
UNLOCK TABLES;
LOCK TABLES `IW_RIGHT` WRITE;
	ALTER TABLE `IW_RIGHT` CHANGE `IW_RIGHT_TO_LAUNCH` `IW_RIGHT_TO_LAUNCH` TINYINT(1) NULL DEFAULT NULL;
UNLOCK TABLES;
LOCK TABLES `IW_USER_DETAILS` WRITE;
	ALTER TABLE `IW_USER_DETAILS`
		CHANGE `IW_ACTIVE` `IW_ACTIVE` TINYINT(1) NULL DEFAULT NULL,
		CHANGE `IW_VISIBLE` `IW_VISIBLE` TINYINT(1) NOT NULL DEFAULT '1';
UNLOCK TABLES;
LOCK TABLES `IW_VARIABLE_PROCESS` WRITE;
	ALTER TABLE `IW_VARIABLE_PROCESS`
		CHANGE `IW_SHOW_TASK_FORM` `IW_SHOW_TASK_FORM` TINYINT(1) NULL DEFAULT NULL,
		CHANGE `IW_SHOW_TASK_LIST` `IW_SHOW_TASK_LIST` TINYINT(1) NULL DEFAULT NULL;
UNLOCK TABLES;
