CREATE TABLE `IW_VARIABLE_TEMPLATE` (
	`IW_VARIABLE_REAL_ID` int(11) NOT NULL AUTO_INCREMENT,
	`IW_VARIABLE_ID` varchar(255) NOT NULL,
	`IW_DESCRIPTION` longtext,
	`IW_LABEL` varchar(250) DEFAULT NULL,
	`IW_FORM_TEMPLATE` int(11) NOT NULL,
	PRIMARY KEY (`IW_VARIABLE_REAL_ID`),
	KEY `IW_FK_VARIABLE_TEMPLATE` (`IW_FORM_TEMPLATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
