LOCK TABLES `RH_POSTE_OCCUPE` WRITE;
ALTER TABLE `RH_POSTE_OCCUPE`
	ADD COLUMN `ID_COLLABORATEUR` INT(11) DEFAULT NULL;
UNLOCK TABLES;

LOCK TABLES `ALD_FORMATION` WRITE;
ALTER TABLE `ALD_FORMATION`
	ADD COLUMN `COLLABORATOR` INT(11) DEFAULT NULL;
UNLOCK TABLES;

LOCK TABLES `RH_COLLABORATEUR` WRITE;
ALTER TABLE `RH_COLLABORATEUR`
	ADD COLUMN `FICHE_DE_POSTE` BIGINT(20) DEFAULT NULL,
	ADD COLUMN `PROMESSE_EMBAUCHE` BIGINT(20) DEFAULT NULL;

ALTER TABLE RH_COLLABORATEUR
	DROP COLUMN DATE_EMBAUCHE,
	DROP COLUMN DATE_NAISSANCE;

ALTER TABLE `RH_COLLABORATEUR`
	ADD COLUMN `DATE_EMBAUCHE` DATE DEFAULT NULL,
    ADD COLUMN `DATE_NAISSANCE` DATE DEFAULT NULL;

UNLOCK TABLES;

ALTER TABLE `RH_POSTE_OCCUPE`
	ADD CONSTRAINT `ALD_FK_COLLABORATEUR_POSTE` FOREIGN KEY (`ID_COLLABORATEUR`) REFERENCES `RH_COLLABORATEUR` (`ID`);


ALTER TABLE `ALD_FORMATION`
	ADD CONSTRAINT `ALD_FK_COLLABORATEUR_FORMATION` FOREIGN KEY (`COLLABORATOR`) REFERENCES `RH_COLLABORATEUR` (`ID`);

ALTER TABLE `RH_COLLABORATEUR`
	ADD CONSTRAINT `ALD_FK_FICHE_POSTE` FOREIGN KEY (`FICHE_DE_POSTE`) REFERENCES `IW_UPLOAD` (`IW_UPLOAD_ID`),
	ADD CONSTRAINT `ALD_FK_PROMESSE_EMBAUCHE` FOREIGN KEY (`PROMESSE_EMBAUCHE`) REFERENCES `IW_UPLOAD` (`IW_UPLOAD_ID`);

