LOCK TABLES `BIZ_FOURNISSEUR` WRITE;
ALTER TABLE `BIZ_FOURNISSEUR`
	ADD COLUMN `ALIAS` VARCHAR(128) DEFAULT NULL AFTER `NOM_HABITUEL`,
	ADD COLUMN `CLASSEMENT_ACHAT` VARCHAR(45) DEFAULT NULL,
	ADD COLUMN `CLASSEMENT_METIER` VARCHAR(45) DEFAULT NULL AFTER `CLASSEMENT_ACHAT`,
	ADD COLUMN `CLASSEMENT_DEFINITIF` VARCHAR(45) DEFAULT NULL AFTER `CLASSEMENT_METIER`,
	ADD COLUMN `JUSTIFICATIF` TEXT DEFAULT NULL,
	ADD COLUMN `MESURE` VARCHAR(128) DEFAULT NULL AFTER `CLASSEMENT_METIER`,
	ADD COLUMN `OFFRE_FINANCIERE` BIGINT(20) DEFAULT NULL,
	ADD COLUMN `OFFRE_TECHNIQUE` BIGINT(20) DEFAULT NULL AFTER `OFFRE_FINANCIERE`,
	ADD COLUMN `TCO_FINANCE` BIGINT(20) DEFAULT NULL AFTER `OFFRE_TECHNIQUE`,
	ADD COLUMN `TCO_PRODUIT` BIGINT(20) DEFAULT NULL AFTER `TCO_FINANCE`,
	ADD COLUMN `SPECIFICATIONS_FONCTIONNELLES` BIGINT(20) DEFAULT NULL AFTER `TCO_PRODUIT`,
	ADD INDEX `FK_BIZ_FOURNISSEUR_IW_UPLOAD_OFFRE_FINANCIERE` (`OFFRE_FINANCIERE`),
	ADD INDEX `FK_BIZ_FOURNISSEUR_IW_UPLOAD_OFFRE_TECHNIQUE` (`OFFRE_TECHNIQUE`),
	ADD INDEX `FK_BIZ_FOURNISSEUR_IW_UPLOAD_TCO_FINANCE` (`TCO_FINANCE`),
	ADD INDEX `FK_BIZ_FOURNISSEUR_IW_UPLOAD_TCO_PRODUIT` (`TCO_PRODUIT`),
	ADD INDEX `FK_BIZ_FOURNISSEUR_IW_UPLOAD_SPECIFICATIONS_FONCTIONNELLES` (`SPECIFICATIONS_FONCTIONNELLES`),
	ADD CONSTRAINT `FK_BIZ_FOURNISSEUR_IW_UPLOAD_OFFRE_FINANCIERE` FOREIGN KEY (`OFFRE_FINANCIERE`) REFERENCES `IW_UPLOAD` (`IW_UPLOAD_ID`),
	ADD CONSTRAINT `FK_BIZ_FOURNISSEUR_IW_UPLOAD_OFFRE_TECHNIQUE` FOREIGN KEY (`OFFRE_FINANCIERE`) REFERENCES `IW_UPLOAD` (`IW_UPLOAD_ID`),
	ADD CONSTRAINT `FK_BIZ_FOURNISSEUR_IW_UPLOAD_TCO_FINANCE` FOREIGN KEY (`TCO_FINANCE`) REFERENCES `IW_UPLOAD` (`IW_UPLOAD_ID`),
	ADD CONSTRAINT `FK_BIZ_FOURNISSEUR_IW_UPLOAD_TCO_PRODUIT` FOREIGN KEY (`TCO_PRODUIT`) REFERENCES `IW_UPLOAD` (`IW_UPLOAD_ID`),
	ADD CONSTRAINT `FK_BIZ_FOURNISSEUR_IW_UPLOAD_SPECIFICATIONS_FONCTIONNELLES` FOREIGN KEY (`SPECIFICATIONS_FONCTIONNELLES`) REFERENCES `IW_UPLOAD` (`IW_UPLOAD_ID`);
UNLOCK TABLES;

LOCK TABLES `BIZ_LIGNE_COMMANDE` WRITE;
ALTER TABLE `BIZ_LIGNE_COMMANDE`
	ADD COLUMN `REFERENCE` VARCHAR(128) DEFAULT NULL AFTER `ID`,
	ADD COLUMN `PRIX_UNITAIRE_ESTIME` DECIMAL (18,2) NULL AFTER `PRIX_UNITAIRE_HT`,
	ADD COLUMN `TOTAL_HORS_TAXE` DECIMAL(18,2) NULL AFTER `TOTAL`;
UNLOCK TABLES;
