CREATE TABLE `RH_EMOLUMENT` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`COLLABORATEUR_ID` int(11) NOT NULL,
	`MOIS` DATE NOT NULL,
	`SALAIRE_BASE` decimal(18,2) DEFAULT NULL,
	`SECURITE_SOCIALE_SALARIE` decimal(18,2) DEFAULT NULL,
	`IRG` decimal(18,2) DEFAULT NULL,
	`PRIME_PANIER` decimal(18,2) DEFAULT NULL,
	`INDEMNITE_EXP_PROF` decimal(18,2) DEFAULT NULL,
	`BONUS_PRIME_RAPPEL` decimal(18,2) DEFAULT NULL,
	`RETENUES_MALADIES_AVANCES` decimal(18,2) DEFAULT NULL,
	`NET_A_PAYER` decimal(18,2) DEFAULT NULL,
	`SECURITE_SOCIALE_EMPLOYEUR` decimal(18,2) DEFAULT NULL,
	PRIMARY KEY (`ID`)
	);

LOCK TABLES `RH_EMOLUMENT` WRITE;
	ALTER TABLE `RH_EMOLUMENT` ADD INDEX(`COLLABORATEUR_ID`);
	ALTER TABLE `RH_EMOLUMENT` ADD FOREIGN KEY (`COLLABORATEUR_ID`) REFERENCES `RH_COLLABORATEUR`(`ID`);
UNLOCK TABLES;
