CREATE TABLE `ALD_FORMATION` (
	`FORMATION_ID` int(11) NOT NULL AUTO_INCREMENT,
	`INTITULE_FORMATION` varchar(50) DEFAULT NULL,
	`PERIODE_FORMATION` varchar(50) DEFAULT NULL,
	`OBJECTIF_FORMATION` varchar(50) DEFAULT NULL,
	`REJECTED` TINYINT(1) NULL,
	`DATE_FORMATION` DATE NULL,
	`EVALUATION_CHAUD` BIGINT(20)  NULL,
	`EVALUATION_FROID` varchar(50) DEFAULT NULL,
	`ATTESTATION` bigint(20) DEFAULT NULL,
	PRIMARY KEY (`FORMATION_ID`),
	KEY `ALD_FK_FORMATION_ATTESTATION` (`ATTESTATION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

ALTER TABLE `ALD_FORMATION`
	ADD CONSTRAINT `ALD_FK_FORMATION_ATTESTATION` FOREIGN KEY (`ATTESTATION`) REFERENCES `IW_UPLOAD` (`IW_UPLOAD_ID`);


