LOCK TABLES `BIZ_ARTICLE` WRITE;
ALTER TABLE `BIZ_ARTICLE`
	DROP FOREIGN KEY `BIZ_FK_ARTICLE_SOUS_FAMILLE`,
	DROP KEY `BIZ_FK_ARTICLE_SOUS_FAMILLE`;
UNLOCK TABLES;

LOCK TABLES `BIZ_SOUS_FAMILLE` WRITE;
DROP TABLE `BIZ_SOUS_FAMILLE`;
UNLOCK TABLES;

LOCK TABLES `BIZ_SRF_SOUS_FAMILLE` WRITE;
DROP TABLE `BIZ_SRF_SOUS_FAMILLE`;
UNLOCK TABLES;

LOCK TABLES `BIZ_SR_FAMILLE` WRITE;
DROP TABLE `BIZ_SR_FAMILLE`;
UNLOCK TABLES;

LOCK TABLES `BIZ_LIGNE_COMMANDE` WRITE;
ALTER TABLE `BIZ_LIGNE_COMMANDE`
	DROP FOREIGN KEY `BIZ_FK_LIGNE_COMMANDE_FAMILLE`,
	DROP KEY `BIZ_FK_LIGNE_COMMANDE_FAMILLE`,
	DROP COLUMN `ID_FAMILLE`;
UNLOCK TABLES;

LOCK TABLES `BIZ_FAMILLE` WRITE;
ALTER TABLE `BIZ_FAMILLE`
	DROP PRIMARY KEY,
	CHANGE `CODE_FAMILLE` `CODE_FAMILLE` VARCHAR (100) NULL,
	ADD COLUMN `ID` INT (11) NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY(`ID`);
UNLOCK TABLES;

LOCK TABLES `BIZ_MAGASIN` WRITE;
ALTER TABLE `BIZ_MAGASIN`
	DROP FOREIGN KEY `BIZ_FK_MAGASIN_SECTEUR`,
	DROP KEY `BIZ_FK_MAGASIN_SECTEUR`,
	CHANGE `SECTEUR` `ID_SECTEUR` BIGINT (20) NULL;
UNLOCK TABLES;

LOCK TABLES `BIZ_SECTEUR_RAYON` WRITE;
ALTER TABLE `BIZ_SECTEUR_RAYON`
	DROP FOREIGN KEY `BIZ_FK_RAYON`,
	DROP KEY `BIZ_FK_RAYON`,
	DROP FOREIGN KEY `BIZ_FK_SECTEUR`,
	DROP KEY `BIZ_FK_SECTEUR`,
	CHANGE `SECTEUR` `ID_SECTEUR` BIGINT (20) NULL,
	CHANGE `RAYON` `ID_RAYON` BIGINT (20) NULL;
UNLOCK TABLES;

LOCK TABLES `BIZ_SECTEUR` WRITE;
ALTER TABLE `BIZ_SECTEUR`
	DROP PRIMARY KEY,
	CHANGE `CODE_SECTEUR` `CODE_SECTEUR` VARCHAR (100) NULL,
	ADD COLUMN `ID` BIGINT (20) NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY(`ID`);
UNLOCK TABLES;

LOCK TABLES `BIZ_RAYON` WRITE;
ALTER TABLE `BIZ_RAYON`
	CHANGE `CODE_RAYON` `CODE_RAYON` VARCHAR (100) NULL,
	DROP PRIMARY KEY, ADD PRIMARY KEY(`ID`),
	CHANGE `ID` `ID` BIGINT (11) NOT NULL AUTO_INCREMENT,
	CHANGE `ID_SECTEUR` `ID_SECTEUR` BIGINT (20) NULL,
	ADD INDEX `BIZ_FK_RAYON_SECTEUR` (`ID_SECTEUR`),
	ADD CONSTRAINT `BIZ_FK_RAYON_SECTEUR` FOREIGN KEY (`ID_SECTEUR`) REFERENCES `BIZ_SECTEUR` (`ID`);
UNLOCK TABLES;

LOCK TABLES `BIZ_MAGASIN` WRITE;
ALTER TABLE `BIZ_MAGASIN`
	ADD INDEX `BIZ_FK_MAGASIN_SECTEUR` (`ID_SECTEUR`),
	ADD CONSTRAINT `BIZ_FK_MAGASIN_SECTEUR` FOREIGN KEY (`ID_SECTEUR`) REFERENCES `BIZ_SECTEUR` (`ID`);
UNLOCK TABLES;

LOCK TABLES `BIZ_SECTEUR_RAYON` WRITE;
ALTER TABLE `BIZ_SECTEUR_RAYON`
	ADD INDEX `BIZ_FK_SECTEUR_RAYON_SECTEUR` (`ID_SECTEUR`),
	ADD CONSTRAINT `BIZ_FK_SECTEUR_RAYON_SECTEUR` FOREIGN KEY (`ID_SECTEUR`) REFERENCES `BIZ_SECTEUR` (`ID`),
	ADD INDEX `BIZ_FK_SECTEUR_RAYON_RAYON` (`ID_RAYON`),
	ADD CONSTRAINT `BIZ_FK_SECTEUR_RAYON_RAYON` FOREIGN KEY (`ID_RAYON`) REFERENCES `BIZ_RAYON` (`ID`);
UNLOCK TABLES;

LOCK TABLES `BIZ_FAMILLE` WRITE;
ALTER TABLE `BIZ_FAMILLE`
	DROP COLUMN `FA_INTITULE`,
	DROP COLUMN `FA_CODE_FAMILLE`,
	DROP COLUMN `FA_ID`,
	DROP COLUMN `FA_DATE_MODIF`,
	CHANGE `ID_RAYON` `ID_RAYON` BIGINT (11) NOT NULL,
	ADD INDEX `BIZ_FK_FAMILLE_RAYON` (`ID_RAYON`),
	ADD CONSTRAINT `BIZ_FK_FAMILLE_RAYON` FOREIGN KEY (`ID_RAYON`) REFERENCES `BIZ_RAYON` (`ID`),
	ADD COLUMN `ID_FAMILLE_PARENT` INT(11) NULL,
	ADD INDEX `BIZ_FK_FAMILLE_FAMILLE` (`ID_FAMILLE_PARENT`),
	ADD CONSTRAINT `BIZ_FK_FAMILLE_FAMILLE` FOREIGN KEY (`ID_FAMILLE_PARENT`) REFERENCES `BIZ_FAMILLE` (`ID`);
UNLOCK TABLES;

CREATE TABLE `BIZ_ACHETEUR` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`ACT_ID_USER` VARCHAR(64) COLLATE utf8_bin NOT NULL DEFAULT '',
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_ACHETEUR_ACT_ID_USER` (`ACT_ID_USER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

LOCK TABLES `BIZ_ACHETEUR` WRITE;
ALTER TABLE `BIZ_ACHETEUR`
	ADD CONSTRAINT `BIZ_FK_ACHETEUR_ACT_ID_USER` FOREIGN KEY (`ACT_ID_USER`) REFERENCES `ACT_ID_USER` (`ID_`);
UNLOCK TABLES;

LOCK TABLES `BIZ_FAMILLE_ACHETEUR` WRITE;
ALTER TABLE `BIZ_FAMILLE_ACHETEUR`
	CHANGE `PA_ID_ACHETEUR` `PA_ID_ACHETEUR` BIGINT (20) NOT NULL,
	CHANGE `PA_ID_FAMILLE` `PA_ID_FAMILLE` INT (11) NOT NULL,
	ADD INDEX `BIZ_FK_FAMILLE_ACHETEUR_ACHETEUR` (`PA_ID_ACHETEUR`),
	ADD CONSTRAINT `BIZ_FK_FAMILLE_ACHETEUR_ACHETEUR` FOREIGN KEY (`PA_ID_ACHETEUR`) REFERENCES `BIZ_ACHETEUR` (`ID`),
	ADD INDEX `BIZ_FK_FAMILLE_ACHETEUR_FAMILLE` (`PA_ID_FAMILLE`),
	ADD CONSTRAINT `BIZ_FK_FAMILLE_ACHETEUR_FAMILLE` FOREIGN KEY (`PA_ID_FAMILLE`) REFERENCES `BIZ_FAMILLE` (`ID`);
UNLOCK TABLES;

CREATE TABLE `BIZ_FAMILLE_FOURNISSEUR` (
	`ID_FA` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`PA_ID_FOURNISSEUR` BIGINT (20) NOT NULL,
	`PA_ID_FAMILLE` INT (11) NOT NULL,
	PRIMARY KEY (`ID_FA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

LOCK TABLES `BIZ_FAMILLE_FOURNISSEUR` WRITE;
ALTER TABLE `BIZ_FAMILLE_FOURNISSEUR`
	ADD INDEX `BIZ_FK_FAMILLE_FOURNISSEUR_FOURNISSEUR` (`PA_ID_FOURNISSEUR`),
	ADD CONSTRAINT `BIZ_FK_FAMILLE_FOURNISSEUR_FOURNISSEUR` FOREIGN KEY (`PA_ID_FOURNISSEUR`) REFERENCES `BIZ_FOURNISSEUR` (`ID`),
	ADD INDEX `BIZ_FK_FAMILLE_FOURNISSEUR_FAMILLE` (`PA_ID_FAMILLE`),
	ADD CONSTRAINT `BIZ_FK_FAMILLE_FOURNISSEUR_FAMILLE` FOREIGN KEY (`PA_ID_FAMILLE`) REFERENCES `BIZ_FAMILLE` (`ID`);
UNLOCK TABLES;

LOCK TABLES `BIZ_ARTICLE` WRITE;
ALTER TABLE `BIZ_ARTICLE`
	DROP COLUMN `AR_SF_ID`,
	DROP COLUMN `AR_DATE_MODIF`,
	CHANGE `AR_REF` `CODE_ARTICLE` VARCHAR (100) NULL,
	ADD COLUMN `LIBELLE` VARCHAR(150) NULL,
	CHANGE `PR_PRIXUNIT` `PRIX_UNIT_HT` DECIMAL (18,2) NULL,
	ADD COLUMN `PRIX_NEGOCIE` DECIMAL (18,2) NULL,
	ADD COLUMN `TVA` DECIMAL (18,2) NULL,
	ADD COLUMN `FAMILLE_ID` INT(11) NULL,
	ADD INDEX `BIZ_FK_ARTICLE_FAMILLE` (`FAMILLE_ID`),
	ADD CONSTRAINT `BIZ_FK_ARTICLE_FAMILLE` FOREIGN KEY (`FAMILLE_ID`) REFERENCES `BIZ_FAMILLE` (`ID`);
UNLOCK TABLES;

LOCK TABLES `BIZ_FOURNISSEUR` WRITE;
ALTER TABLE `BIZ_FOURNISSEUR`
	DROP COLUMN `INTITULE`,
	DROP COLUMN `UK`,
	DROP COLUMN `CLASSEMENT_ACHAT`,
	DROP COLUMN `CLASSEMENT_METIER`,
	DROP COLUMN `CLASSEMENT_DEFINITIF`,
	DROP FOREIGN KEY `FK_BIZ_FOURNISSEUR_IW_UPLOAD_OFFRE_FINANCIERE`,
	DROP FOREIGN KEY `FK_BIZ_FOURNISSEUR_IW_UPLOAD_OFFRE_TECHNIQUE`,
	DROP KEY `FK_BIZ_FOURNISSEUR_IW_UPLOAD_OFFRE_FINANCIERE`,
	DROP KEY `FK_BIZ_FOURNISSEUR_IW_UPLOAD_OFFRE_TECHNIQUE`,
	DROP COLUMN `OFFRE_FINANCIERE`,
	DROP COLUMN `OFFRE_TECHNIQUE`,
	CHANGE `NOM_COMMERCIAL` `RAISON_SOCIAL` VARCHAR (100) NULL,
	CHANGE `NOM_HABITUEL` `NOM_HABITUEL` VARCHAR (100) NULL,
	ADD COLUMN `STATUT` VARCHAR (50) NULL,
	ADD COLUMN `TEL` VARCHAR (50) NULL,
	ADD COLUMN `FAX` VARCHAR (50) NULL,
	ADD COLUMN `EMAIL` VARCHAR (50) NULL,
	ADD COLUMN `REPRESENTANT` VARCHAR (50) NULL;
UNLOCK TABLES;

LOCK TABLES `BIZ_LIGNE_COMMANDE` WRITE;
ALTER TABLE `BIZ_LIGNE_COMMANDE`
	DROP COLUMN `ID_CATEGORIE`,
	DROP COLUMN `ID_PROCESS`,
	DROP COLUMN `ID_PRODUIT`,
	DROP COLUMN `DEROGATION_BUDGET`,
	DROP COLUMN `VALIDATION_BUDGET`;
UNLOCK TABLES;

CREATE TABLE `BIZ_DEMANDE_ACHAT` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`DATE_CREATION` date DEFAULT NULL,
	`DATE_SOUHAITEE` date DEFAULT NULL,
	`MODE_PAIEMENT` VARCHAR(50) DEFAULT NULL,
	`MOTIF` VARCHAR(20) DEFAULT NULL,
	`NOM_PROJET` VARCHAR(50) DEFAULT NULL,
	`REFFERENCE_CLIENT` VARCHAR(50) DEFAULT NULL,
	`TYPE_CLIENT` VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `BIZ_LIGNE_DEMANDE_ACHAT` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`DESCRIPTION` VARCHAR(250) DEFAULT NULL,
	`QUANTITE` INT(11) DEFAULT NULL,
	`TOTAL` DECIMAL(18,2) DEFAULT NULL,
	`ID_ARTICLE` BIGINT(20) DEFAULT NULL,
	`ID_ACHAT` BIGINT(20) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_LIGNE_DEMANDE_ACHAT_ARTICLE` (`ID_ARTICLE`),
	KEY `BIZ_FK_LIGNE_DEMANDE_ACHAT_DEMAND_ACHAT` (`ID_ACHAT`),
	CONSTRAINT `BIZ_FK_LIGNE_DEMANDE_ACHAT_ARTICLE` FOREIGN KEY (`ID_ARTICLE`) REFERENCES `BIZ_ARTICLE` (`AR_ID`),
	CONSTRAINT `BIZ_FK_LIGNE_DEMANDE_ACHAT_DEMAND_ACHAT` FOREIGN KEY (`ID_ACHAT`) REFERENCES `BIZ_DEMANDE_ACHAT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `BIZ_LIGNE_COMMANDE` WRITE;
ALTER TABLE `BIZ_LIGNE_COMMANDE`
	ADD COLUMN `LIGNE_DEMANDE_ID` BIGINT(20) NULL,
	ADD COLUMN `LIGNE_DEMANDE_QUATITE` INT(11) DEFAULT NULL,
	ADD INDEX `BIZ_FK_LIGNE_COMMANDE` (`LIGNE_DEMANDE_ID`),
	ADD CONSTRAINT `BIZ_FK_REGLEMENT_LIGNE_COMMANDE` FOREIGN KEY (`LIGNE_DEMANDE_ID`) REFERENCES `BIZ_LIGNE_COMMANDE` (`ID`);
UNLOCK TABLES;

LOCK TABLES `BIZ_REGLEMENT` WRITE;
ALTER TABLE `BIZ_REGLEMENT`
	ADD COLUMN `LIGNE_COMMANDE_ID` BIGINT(20) NULL,
	ADD INDEX `BIZ_FK_REGLEMENT_LIGNE_COMMANDE_LIGNE_DEMANDE_ACHAT` (`LIGNE_COMMANDE_ID`),
	ADD CONSTRAINT `BIZ_FK_REGLEMENT_LIGNE_COMMANDE_LIGNE_DEMANDE_ACHAT` FOREIGN KEY (`LIGNE_COMMANDE_ID`) REFERENCES `BIZ_LIGNE_DEMANDE_ACHAT` (`ID`);
UNLOCK TABLES;

CREATE TABLE `BIZ_LIGNE_COMMANDE_PROCESS` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`LIGNE_COMMANDE_ID` BIGINT (20) NOT NULL,
	`CODE_BUDGET` VARCHAR(45) DEFAULT NULL,
	`VALIDATION_BUDGET` TINYINT(1) DEFAULT '0',
	`PROCESS_ID` VARCHAR(64) NOT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `BIZ_FOURNISSEUR_PROCESS` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`FOURNISSEUR_ID` BIGINT(20) NOT NULL,
	`CLASSEMENT_ACHAT` VARCHAR(75) NULL,
	`CLASSEMENT_METIER` VARCHAR(75) NULL,
	`CLASSEMENT_DEFINITIF` VARCHAR(75) NULL,
	`OFFRE_FINANCIERE` VARCHAR(75) NULL,
	`OFFRE_TECHNIQUE` VARCHAR(75) NULL,
	PRIMARY KEY (`ID`),
	KEY `BIZ_FK_FOURNISSEUR_PROCESS_FOURNISSEUR` (`FOURNISSEUR_ID`),
	CONSTRAINT `BIZ_FK_FOURNISSEUR_PROCESS_FOURNISSEUR` FOREIGN KEY (`FOURNISSEUR_ID`) REFERENCES `BIZ_FOURNISSEUR` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
