LOCK TABLES `RH_CONGE` WRITE;
	ALTER TABLE `RH_CONGE`

	ADD COLUMN `COLLABORATEUR` int(11) DEFAULT NULL ;

UNLOCK TABLES;

ALTER TABLE `RH_CONGE`
    ADD CONSTRAINT `ALD_FK_COLLABORATEUR` FOREIGN KEY (`COLLABORATEUR`) REFERENCES `RH_COLLABORATEUR` (`ID`);
