LOCK TABLES `RH_FORMATION` WRITE;
	ALTER TABLE `RH_FORMATION`
		ADD COLUMN  `INTITULE_FORMATION` varchar(50) DEFAULT NULL,
		ADD COLUMN  `DATE_FORMATION` DATE NULL,
		ADD COLUMN  `COLLABORATOR` int(11) DEFAULT NULL,
		ADD COLUMN  `ATTESTATION` bigint(20) DEFAULT NULL;
UNLOCK TABLES;

ALTER TABLE `RH_FORMATION`
	ADD CONSTRAINT `ALD_FK_COLLABORATEUR_RHFORMATION` FOREIGN KEY (`COLLABORATOR`) REFERENCES `RH_COLLABORATEUR` (`ID`),
	ADD CONSTRAINT `ALD_FK_RHFORMATION_ATTESTATION` FOREIGN KEY (`ATTESTATION`) REFERENCES `IW_UPLOAD` (`IW_UPLOAD_ID`);
