LOCK TABLES `RH_COLLABORATEUR` WRITE;
ALTER TABLE `RH_COLLABORATEUR`
	ADD COLUMN `CLASSIFICATION_INTERNE` LONGTEXT DEFAULT NULL,
	ADD COLUMN `NIVEAU_ETUDE` VARCHAR(20) DEFAULT NULL,
	ADD COLUMN `NUM_PASSEPORT` VARCHAR(20) DEFAULT NULL,
	ADD COLUMN `RIB` VARCHAR(20) DEFAULT NULL,
	ADD COLUMN `CONTRAT` BIGINT(20) DEFAULT NULL;
UNLOCK TABLES;

ALTER TABLE `RH_COLLABORATEUR`
	ADD CONSTRAINT `ALD_FK_CONTRAT` FOREIGN KEY (`CONTRAT`) REFERENCES `IW_UPLOAD` (`IW_UPLOAD_ID`);
