LOCK TABLES `BIZ_LIGNE_COMMANDE` WRITE;
ALTER TABLE `BIZ_LIGNE_COMMANDE`
	ADD COLUMN  `DATE_DEBUT_UTILISATION` date DEFAULT NULL,
	ADD COLUMN  `DATE_FIN_UTILISATION` date DEFAULT NULL,
	ADD COLUMN  `TAUX` decimal(18,2) DEFAULT NULL;
UNLOCK TABLES;
